/**
 * 아이콘 이름에 쓰인 영어 낱말의 한국어 대역어. **자동 생성 — 손대지 말 것.**
 *
 *   bun run scripts/bake-icon-keywords.mjs
 *
 * 손으로 쓴 `ICON_KEYWORDS_KO`가 언제나 먼저다. 여기는 그 사전이 놓친 자리를 메운다 —
 * 사람이 고른 순서를 자동 생성이 밀어내면 안 되기 때문이다.
 *
 * 값은 그 낱말이 **아이콘 이름에 몇 번 나오는지** 순으로 놓았다. 잦은 것이 그 개념의
 * 대표일 확률이 높다("냉장고"의 `refrigerator`가 `fridge`보다 앞이다).
 *
 * 뜻풀이는 영어 위키낱말사전(Wiktionary)에서 왔고 CC BY-SA 4.0이다. kaikki.org가
 * 뽑아 둔 기계 판독본을 썼다. 서버에서만 읽는다 — 브라우저 묶음에 들어가지 않는다.
 *
 * 표제어 3747개 · 영어 낱말 1979개 · 생성 2026-08-11
 */

export const ICON_KEYWORDS_GENERATED: Readonly<Record<string, readonly string[]>> = {
  가각: ["corner", "corners"],
  가게: ["shop"],
  가격: ["price"],
  가구: ["block", "blocks"],
  가군: ["module"],
  가극: ["opera"],
  가극단: ["opera"],
  가나: ["kana"],
  가라데: ["karate"],
  가락지: ["ring", "rings"],
  가래: ["spade"],
  가려움증: ["itch"],
  가면: ["mask", "masks"],
  가명: ["alias"],
  가방: ["bag", "briefcase", "handbag", "bags"],
  가사: ["lyrics"],
  가스: ["gas"],
  가슴: ["chest"],
  가시: ["quill"],
  가열기: ["heater"],
  가운데: ["middle"],
  가위: ["scissors"],
  가이드: ["guide", "guides"],
  가입하다: ["admission"],
  가정: ["family"],
  가족: ["family", "people"],
  가죽: ["hide"],
  가지: ["branch"],
  가축: ["stock"],
  가타가나: ["katakana"],
  가타카나: ["katakana"],
  가판대: ["kiosk"],
  각기둥: ["prism"],
  각도: ["angle"],
  각본: ["script"],
  각뿔: ["pyramid"],
  간각: ["gap"],
  간극: ["gap"],
  간첩: ["spy"],
  간통: ["gap"],
  간판: ["sign", "signs"],
  간호사: ["nurse"],
  간호원: ["nurse"],
  갈고리: ["hook"],
  갈대: ["cane"],
  갈등: ["conflict"],
  갈림길: ["fork"],
  갈망: ["itch"],
  갈비: ["rib"],
  갈아탐: ["change", "changes"],
  갈퀴: ["fork"],
  감각: ["sense"],
  감귤류: ["citrus"],
  감기: ["cold"],
  감독: ["directions", "direction", "director"],
  감독자: ["supervisor"],
  감상문: ["review", "reviews"],
  감옥: ["prison"],
  감자칩: ["chip", "chips"],
  감정: ["emotion"],
  갑각: ["shell"],
  갑충: ["beetle"],
  갑판: ["deck"],
  강국: ["power"],
  강냉이: ["tooth"],
  강삭철도: ["funicular"],
  강설: ["snow"],
  강세: ["emphasis"],
  강아지: ["dog"],
  강의: ["talk"],
  강조: ["emphasis", "stress"],
  강풍: ["gale"],
  강하: ["fallout"],
  개같은놈: ["dog"],
  개관: ["survey"],
  개념: ["notion"],
  개발자: ["developer"],
  개선: ["improvement"],
  개요: ["overview", "summary"],
  개울: ["stream"],
  개인: ["person", "individual"],
  개체: ["individual"],
  개털: ["trash"],
  개폐기: ["switch"],
  객사: ["hotel", "hotels"],
  객실: ["cabin"],
  객차: ["van"],
  객체: ["object", "objects"],
  갤러리: ["gallery"],
  갱도: ["tunnel"],
  갱신: ["update", "updates"],
  거듭제곱: ["power"],
  거듭제곱근: ["root"],
  거래: ["transaction"],
  거래소: ["exchange"],
  거리: ["distance"],
  거물: ["wheel"],
  거미: ["spider"],
  거북: ["turtle"],
  거스름돈: ["change", "changes"],
  거울: ["mirror"],
  거품: ["bubble", "bubbles"],
  거품기: ["whisk"],
  건강: ["health"],
  건강검진: ["physical"],
  건락: ["cheese"],
  건물: ["building", "buildings"],
  건반: ["keyboard", "key", "keys"],
  건설: ["building", "buildings", "construction"],
  건조기: ["dryer"],
  건축: ["architecture"],
  건축학: ["architecture"],
  걷기: ["walking"],
  걸상: ["stool"],
  걸음: ["step", "steps"],
  걸음새: ["walk"],
  검사: ["check", "test", "checks", "inspection"],
  검색: ["search"],
  검은딸기: ["blackberry"],
  게시물: ["post"],
  게임: ["game", "games"],
  겨를: ["room", "rooms"],
  격자: ["grid"],
  견과: ["nut"],
  견본: ["sample"],
  견신: ["confirmation"],
  견신례: ["confirmation"],
  견지: ["angle"],
  결과: ["end", "work", "product", "effects"],
  결론: ["end"],
  결말: ["end"],
  결석: ["stone"],
  결절: ["node"],
  결정: ["crystal"],
  결합: ["join"],
  결혼: ["union"],
  겹빵이: ["sandwich"],
  경계: ["border"],
  경계표: ["landmark"],
  경고: ["warning"],
  경관: ["landscape"],
  경기: ["game", "match", "games"],
  경기대회: ["tournament"],
  경기장: ["park", "stadium"],
  경도: ["longitude"],
  경로: ["route"],
  경매: ["auction"],
  경보: ["alarm"],
  경보기: ["siren"],
  경선: ["longitude"],
  경야: ["wake"],
  경영자: ["manager"],
  경우: ["case", "cases"],
  경음기: ["speaker", "megaphone"],
  경찰: ["police"],
  경축: ["celebration"],
  경치: ["view", "sight"],
  경향: ["trend"],
  경험: ["time", "times"],
  계급: ["class", "rank"],
  계기판: ["dashboard"],
  계단: ["stairs"],
  계단승강기: ["escalator"],
  계란: ["egg", "eggs"],
  계량: ["metrics", "measure"],
  계량기: ["meter", "gauge"],
  계산기: ["calculator"],
  계산대: ["counter"],
  계산서: ["check", "checks", "invoice", "bill"],
  계약: ["contract"],
  계좌: ["account", "accounts"],
  계집: ["woman"],
  계집애: ["broad"],
  계층: ["class", "hierarchy"],
  계통: ["system"],
  계획: ["program", "design", "blueprint", "plan"],
  계획자: ["planner"],
  고객: ["customer"],
  고객님: ["customer"],
  고글: ["goggles"],
  고기: ["fish", "meat"],
  고기겹빵: ["hamburger"],
  고도: ["height"],
  고리: ["link", "basket", "ring", "loop"],
  고리짝: ["basket"],
  고무: ["rubber"],
  고물상: ["pawn"],
  고뿌: ["glass", "cup"],
  고뿔: ["cold"],
  고성기: ["speaker"],
  고스트: ["ghost"],
  고양이: ["cat"],
  고인: ["deceased"],
  고체: ["solids"],
  고추: ["pepper"],
  고향: ["home"],
  곡마단: ["circus"],
  곡물: ["grains", "grain"],
  곡선: ["curve"],
  곡조: ["tune"],
  곡척: ["square", "squares"],
  곤돌라: ["gondola"],
  곤포: ["package", "packages"],
  골격: ["skeleton"],
  골목: ["close", "lane"],
  골절: ["fracture"],
  골프: ["golf"],
  공간: ["space", "area", "room", "rooms"],
  공격수: ["forward"],
  공공: ["public"],
  공구: ["tools", "tool"],
  공구함: ["toolbox"],
  공기: ["air"],
  공동체: ["community"],
  공란: ["blank"],
  공문서: ["archive"],
  공백: ["space", "spaces"],
  공변량: ["covariate"],
  공산주의자: ["red"],
  공색: ["azure"],
  공수도: ["karate"],
  공식: ["formula"],
  공연: ["performance"],
  공용계단: ["close"],
  공원: ["park"],
  공장: ["factory"],
  공제액: ["credit", "credits"],
  공책: ["notebook"],
  공청회: ["hearing"],
  공학: ["engineering"],
  공항: ["airports", "airport"],
  공항터미널: ["terminal"],
  과녁: ["target"],
  과목: ["subject"],
  과실주: ["wine"],
  과자: ["cake"],
  과정: ["course", "process"],
  과제: ["task", "problem"],
  과태료: ["fine"],
  과학: ["science"],
  관계: ["relation"],
  관광가이드: ["guide", "guides"],
  관광객: ["visitor"],
  관례: ["routine"],
  관로: ["pipeline"],
  관리: ["management"],
  관리자: ["admin", "manager"],
  관목: ["shrub"],
  관사: ["article"],
  관심: ["interests"],
  관자놀이: ["temple"],
  관점: ["view", "angle"],
  관청: ["office"],
  괄호: ["brackets"],
  광고: ["advertisement"],
  광구: ["photosphere"],
  광명: ["lamp"],
  광선: ["beam"],
  광장: ["square", "squares", "places", "place"],
  괴뢰: ["satellite"],
  굉음: ["crash"],
  교구: ["see"],
  교대: ["shift"],
  교도소: ["prison"],
  교량: ["bridge"],
  교류: ["exchange"],
  교리: ["doctrine"],
  교사: ["teacher"],
  교섭: ["talk"],
  교신: ["traffic"],
  교양: ["education"],
  교육: ["education"],
  교의: ["doctrine"],
  교자: ["dumpling"],
  교전: ["action", "actions"],
  교점: ["intersection", "node"],
  교집합: ["intersection"],
  교차로: ["intersection"],
  교통: ["traffic", "transportation"],
  교통기관: ["transportation"],
  교편: ["pointer"],
  교화소: ["prison"],
  교환: ["swap", "exchange"],
  교회: ["church"],
  교훈: ["lesson"],
  구경: ["sight"],
  구급차: ["ambulance"],
  구독: ["subscriptions"],
  구름: ["cloud"],
  구리: ["copper"],
  구리쇠: ["copper"],
  구사: ["command", "commands"],
  구석: ["corner", "corners", "angle"],
  구성: ["structure", "plot"],
  구역: ["zone", "block", "blocks"],
  구유: ["crib"],
  구조: ["structure"],
  구체: ["sphere"],
  구타: ["battery"],
  구형: ["rectangle", "rectangles"],
  국가: ["land"],
  국경: ["border"],
  국계: ["border"],
  국민: ["people"],
  국왕: ["king", "kings"],
  국자: ["ladle"],
  국제정당: ["international"],
  국제정당조직: ["international"],
  군대: ["military"],
  군마: ["charger"],
  군집: ["community"],
  군호: ["password"],
  굳은모: ["hardware"],
  궁도: ["archery"],
  궁륭: ["vault"],
  궁비: ["queen"],
  궁술: ["archery"],
  궁정: ["court"],
  권고: ["recommendations"],
  권력: ["power"],
  권리: ["rights"],
  권투: ["boxing"],
  궐련: ["cigarette"],
  궤도: ["orbit"],
  귀뚜라미: ["cricket"],
  귀신: ["ghost"],
  귀퉁이: ["angle"],
  규률: ["rule"],
  규모: ["scale"],
  규약: ["code"],
  규율: ["rule"],
  규칙: ["rule"],
  그늘: ["shadow", "shades", "shade"],
  그래프: ["graph", "plot"],
  그래픽: ["graphics"],
  그루빠: ["group", "groups"],
  그룹: ["group", "groups", "band"],
  그릇: ["bowl", "container"],
  그리드: ["grid"],
  그릴: ["grill"],
  그림: ["picture"],
  그림자: ["shadow", "shades", "shade"],
  그물: ["network", "mesh"],
  극간: ["gap"],
  극장: ["theater", "theaters", "cinema"],
  근원: ["root"],
  근친자: ["people"],
  글꼴: ["font"],
  글라스: ["glass"],
  글루코스: ["glucose"],
  글쇠판: ["keyboard"],
  글씨: ["letter", "character", "letters"],
  글자: ["letter", "character", "letters"],
  금고: ["chest", "safe"],
  금속: ["metal"],
  금액: ["sum"],
  금융: ["finance"],
  금일: ["today"],
  금자탑: ["pyramid"],
  금전: ["money"],
  금지: ["ban"],
  급장: ["monitor"],
  급진파: ["radical"],
  기간: ["duration"],
  기계: ["machine"],
  기관: ["engine", "motor"],
  기구: ["balloon", "machine", "organization"],
  기금: ["funds"],
  기념비: ["monument"],
  기능: ["function", "functions"],
  기도: ["prayer"],
  기도학: ["pulmonology"],
  기둥: ["columns", "column", "post"],
  기록: ["note", "notes", "record"],
  기름: ["gas", "oil"],
  기물: ["piece"],
  기발: ["flag", "banner"],
  기분: ["mood"],
  기사: ["article", "news", "knight"],
  기사단: ["order", "orders"],
  기술: ["description"],
  기어박스: ["gearbox"],
  기억: ["memory"],
  기업: ["business", "enterprise"],
  기온: ["temperature"],
  기와: ["tile"],
  기울: ["meal", "meals"],
  기원: ["origin"],
  기저귀: ["diaper"],
  기정사실: ["fact"],
  기준: ["standard"],
  기중기: ["crane"],
  기지: ["base"],
  기지개: ["stretch"],
  기차: ["train"],
  기체: ["gas"],
  기초: ["base", "foundation"],
  기치: ["flag", "banner"],
  기타: ["guitar"],
  기하학: ["geometry"],
  기호: ["character", "symbols"],
  기후: ["climate"],
  길이: ["length"],
  길잡이: ["guide", "guides"],
  깁스: ["cast"],
  깃발: ["flag", "banner"],
  깃털: ["feather"],
  깃털펜: ["quill"],
  깃펜: ["quill"],
  까벨: ["cable"],
  깔개: ["rug"],
  깔때기: ["funnel"],
  깜빠니아: ["campaign"],
  깜빡이: ["indicator"],
  깡통: ["can"],
  깨짐: ["crash"],
  껍질: ["shell"],
  꼬리: ["tail"],
  꼬마: ["boy"],
  꼬부랑국수: ["ramen"],
  꽃구경: ["hanami"],
  꽃집: ["florist"],
  꾸러미: ["package", "packet", "packages"],
  끄트러기: ["snippet"],
  끝세로줄: ["close"],
  끼니: ["meal", "meals"],
  끽연: ["smoking"],
  나가는곳: ["exit"],
  나라: ["land"],
  나루배: ["ferry"],
  나룻배: ["ferry"],
  나머지: ["rest"],
  나무: ["tree", "trees", "wood"],
  나뭇가지: ["stick", "branch", "twig"],
  나비: ["butterfly"],
  나비매듭: ["bow"],
  나사돌리개: ["screwdriver"],
  나선: ["spiral"],
  나선형: ["spiral"],
  나이트: ["knight"],
  나이트클럽: ["club"],
  나이프: ["knife"],
  나침반: ["compass"],
  낙하: ["fallout"],
  낙하산: ["parachute"],
  낚시: ["fishing"],
  낚시대: ["rod"],
  낚싯대: ["rod"],
  난각: ["shell"],
  난로: ["fireplace"],
  난문: ["puzzle"],
  난방기: ["heater"],
  난제: ["puzzle"],
  날기: ["flight", "flights"],
  날씨: ["weather"],
  날짜: ["date"],
  남방: ["shirt"],
  남배우: ["actors"],
  남성: ["male"],
  남우: ["actors"],
  남자: ["man"],
  남자아이: ["boy"],
  남자애: ["boy"],
  남쪽: ["south"],
  납유리: ["crystal"],
  납촉: ["candle"],
  낯짝: ["mug"],
  낱말: ["word"],
  낱장: ["leaf"],
  내려받기: ["download"],
  내림표: ["flat"],
  내부: ["inside"],
  내분비학: ["endocrinology"],
  내비게이션: ["navigation"],
  내선: ["extension"],
  내용: ["content", "contents"],
  냄비: ["pot"],
  냉장고: ["refrigerator"],
  너트: ["nut"],
  네거리: ["intersection"],
  네트워크: ["network"],
  녀성: ["woman"],
  녀왕: ["queen"],
  녀인: ["woman"],
  녀자: ["woman", "girl"],
  녀자아이: ["girl"],
  년월일: ["date"],
  노동: ["work"],
  노드: ["node"],
  노력: ["work"],
  노면전차: ["tram"],
  노뼈: ["radius"],
  노선: ["route"],
  노이즈: ["noise"],
  노임: ["price"],
  노출: ["exposure"],
  노트: ["note", "notes", "notebook"],
  노트북: ["laptop", "notebook"],
  노트패드: ["notepad"],
  녹색: ["green"],
  녹음: ["recording"],
  논단: ["forum"],
  논리: ["logic"],
  논리학: ["logic"],
  논문: ["article"],
  논평: ["comment", "comments"],
  놀이: ["play", "game", "games"],
  놀이터: ["playground"],
  농구: ["basketball"],
  농구공: ["basketball"],
  농사: ["agriculture"],
  농업: ["agriculture"],
  농장: ["farm"],
  높은지위: ["status"],
  높이: ["height"],
  뇌수: ["brain"],
  뇌우: ["thunderstorm", "thunderstorms"],
  누두: ["funnel"],
  누리: ["world"],
  누설: ["leak"],
  눈곱: ["sleep"],
  눈금: ["scale"],
  눈금자: ["ruler"],
  눈꽃: ["snowflake"],
  눈사람: ["snowman"],
  눈섭: ["eyebrow"],
  눈송이: ["snowflake"],
  눈썹: ["eyebrow"],
  뉴스: ["news"],
  뉴스캐스터: ["anchor"],
  느림보: ["snail"],
  늑골: ["rib"],
  능력: ["capacity"],
  다각형: ["polygon"],
  다관: ["teapot"],
  다다미: ["tatami"],
  다람쥐: ["squirrel"],
  다름: ["difference"],
  다리: ["bridge"],
  다리미질: ["ironing"],
  다림질: ["ironing"],
  다면체: ["polyhedron"],
  다엽: ["tea"],
  다운: ["download"],
  다운로드: ["download"],
  다이빙: ["diving"],
  다이아몬드: ["diamond", "diamonds"],
  다이오드: ["diode"],
  다크서클: ["circle", "circles"],
  단거리경주: ["sprint"],
  단거리달리기: ["sprint"],
  단결: ["unity"],
  단계: ["step", "steps", "stage"],
  단골집: ["hangout"],
  단락: ["paragraph"],
  단락기호: ["pilcrow"],
  단말: ["terminal"],
  단말기: ["terminal"],
  단어: ["language", "word", "languages"],
  단위: ["credit", "unit", "credits"],
  단일: ["unity"],
  단지: ["jar", "pot"],
  단체: ["band", "organization"],
  단추: ["button", "buttons"],
  단타: ["single"],
  단편: ["snippet"],
  단풍나무: ["maple"],
  단행본: ["volume"],
  달걀: ["egg", "eggs"],
  달걀꼴: ["oval"],
  달구지: ["cart"],
  달러: ["dollar"],
  달력: ["calendar", "calendars"],
  달리기: ["running"],
  달팽이: ["snail"],
  담배: ["cigarette", "smoke"],
  담보: ["deposit"],
  담요: ["blanket"],
  답변: ["reply", "answer"],
  답사: ["exploration"],
  답안: ["answer"],
  당고: ["dango"],
  당구: ["billiards"],
  당근: ["carrot"],
  대걸레: ["mop"],
  대기줄: ["queue"],
  대답: ["reply", "answer"],
  대리: ["proxy"],
  대리인: ["agent", "agents"],
  대마: ["cannabis"],
  대문: ["gate"],
  대변: ["stool"],
  대본: ["script"],
  대상: ["object", "objects", "caravan"],
  대성당경내: ["close"],
  대수: ["flood"],
  대시보드: ["dashboard"],
  대역폭: ["band"],
  대요: ["summary"],
  대장: ["general"],
  대조: ["check", "checks"],
  대중: ["public"],
  대지: ["earth"],
  대추: ["date"],
  대패: ["plane"],
  대표단: ["delegation"],
  대피소: ["shelter"],
  대학: ["school", "university"],
  대학교: ["school", "university"],
  대화: ["talk", "conversation"],
  댓글: ["comment", "reply", "comments"],
  더듬이: ["antenna"],
  더미: ["heap"],
  더위: ["heat"],
  덕후: ["fan"],
  덤벨: ["dumbbell"],
  덧문: ["shutter"],
  덮는범위: ["coverage"],
  데스크톱: ["desktop"],
  데스크톱컴퓨터: ["desktop"],
  데이터: ["data"],
  데이터베이스: ["database"],
  데이트: ["date"],
  델타: ["delta"],
  도구: ["tools", "tool"],
  도구모음: ["toolbar"],
  도구상자: ["toolbox"],
  도끼: ["axe", "axes"],
  도달: ["arrival"],
  도달점: ["end"],
  도둑질: ["theft"],
  도로: ["road"],
  도료: ["paint"],
  도마: ["vault"],
  도막: ["bit"],
  도메인: ["domain", "domains"],
  도박장: ["casino"],
  도서: ["book", "books"],
  도서관: ["library"],
  도시: ["city"],
  도시철도: ["subway"],
  도약: ["jump"],
  도어폰: ["doorbell"],
  도우미: ["help", "assistant", "helper"],
  도움: ["help"],
  도움말: ["help"],
  도작: ["plagiarism"],
  도장: ["seal", "stamp"],
  도착: ["arrival"],
  도청기: ["bug", "bugs"],
  도청장치: ["bug", "bugs"],
  도큐먼트: ["document"],
  도토리: ["acorn"],
  도표: ["chart", "graph", "plot"],
  도해: ["plan"],
  도화: ["picture"],
  독방: ["cell", "cells"],
  독본: ["reader"],
  독신: ["single"],
  독신자: ["single"],
  독자: ["reader"],
  독트린: ["doctrine"],
  돌격: ["charge"],
  돌기: ["turn"],
  돌리기: ["turn"],
  동그라미: ["circle", "circles"],
  동력: ["energy"],
  동료: ["partner"],
  동맹: ["union"],
  동무: ["friends"],
  동반자: ["partner"],
  동아리: ["club"],
  동일성: ["identity"],
  동일함: ["identity"],
  동전: ["coin", "coins"],
  동점골: ["equalizer"],
  동쪽: ["east"],
  동호회: ["club"],
  돼지: ["pig"],
  두개골: ["skull"],
  두건: ["hood"],
  두뇌: ["brain", "head"],
  두루마리: ["scroll"],
  두루미: ["crane"],
  두묘: ["vaccines", "vaccine"],
  두문자: ["initial"],
  두정: ["crown"],
  둥지: ["nest"],
  뒤집개: ["spatula"],
  뒤쪽: ["back"],
  뒤틀기: ["wrench"],
  뒷간: ["toilet"],
  드라마: ["drama"],
  드라이버: ["screwdriver"],
  드라이브: ["drive", "drives"],
  드럼: ["drum"],
  드럼스틱: ["drumstick"],
  드레스: ["dress"],
  드론: ["drone"],
  드릴: ["drill"],
  드링크: ["beverage"],
  득점: ["score"],
  득점판: ["scoreboard"],
  듣보잡: ["random"],
  들판: ["fields", "field"],
  등걸불: ["ember"],
  등급: ["rating", "class", "degrees", "grade"],
  등기: ["registration"],
  등대: ["lighthouse"],
  등록: ["registration"],
  등불: ["lamp", "flashlight"],
  등산: ["hike", "hiking"],
  등산로: ["trail"],
  등장인물: ["character"],
  디나르: ["dinar"],
  디렉토리: ["folder", "folders", "directory"],
  디르함: ["dirham"],
  디바이스: ["device", "devices"],
  디스코: ["disco"],
  디스크: ["disk"],
  디스플레이: ["display", "displays"],
  디시: ["dish"],
  디자인: ["design"],
  디저트: ["dessert"],
  디폴트: ["default"],
  따옴표: ["quote", "quotes"],
  딱씨: ["taxi"],
  땅거미: ["twilight"],
  땅굴: ["tunnel"],
  땅콩: ["peanut"],
  땅크: ["tank"],
  땔나무: ["wood"],
  뗀노: ["computer"],
  뚜껑: ["cap"],
  뚫어뻥: ["plunger"],
  뜨락또르: ["tractor"],
  라디오: ["radio"],
  라디오수신기: ["radio"],
  라멘: ["ramen"],
  라면: ["ramen"],
  라벨: ["label", "sticker", "stickers"],
  라선: ["spiral"],
  라선형: ["spiral"],
  라우터: ["router"],
  라이브러리: ["library"],
  라이선스: ["license"],
  라이센스: ["license"],
  라이터: ["lighter"],
  라인: ["lines"],
  라지오: ["radio"],
  라침반: ["compass"],
  락하: ["fallout"],
  락하산: ["parachute"],
  란각: ["shell"],
  람다: ["lambda"],
  랍촉: ["candle"],
  랜드마크: ["landmark"],
  랜드스케이프: ["landscape"],
  랜야드: ["lanyard"],
  램프: ["lamp", "ramp"],
  랩탑: ["laptop"],
  랩톱: ["laptop"],
  랭장고: ["refrigerator"],
  랭크: ["rank"],
  랭킹: ["ranking"],
  럭비: ["rugby"],
  럭스: ["lux"],
  런닝머신: ["treadmill"],
  런민비: ["renminbi"],
  런치: ["lunch"],
  레드와인: ["red"],
  레몬: ["lemon"],
  레몬나무: ["lemon"],
  레몬색: ["lemon"],
  레벨: ["level"],
  레스토랑: ["restaurant"],
  레알: ["real"],
  레우: ["leu"],
  레이다: ["radar"],
  레이블: ["label"],
  레이어: ["layers", "layer"],
  레이저: ["laser"],
  레이팅: ["rating"],
  레일: ["rail"],
  레코드: ["record", "disk", "vinyl"],
  레포트: ["report", "reports"],
  렌즈: ["contact", "contacts", "lens"],
  렌털: ["rental"],
  려객: ["fare"],
  려과기: ["filter", "filters"],
  려관: ["hotel", "hotels"],
  려권: ["passport"],
  려정: ["trips", "trip"],
  려행: ["travel", "trips", "trip"],
  력법: ["calendar", "calendars"],
  력사: ["history"],
  련결: ["link", "connection", "links"],
  련락: ["contact", "contacts"],
  련맹: ["union"],
  련습: ["exercise"],
  련와: ["brick"],
  련인: ["flame"],
  렬차: ["train"],
  령수증: ["receipt"],
  령역: ["domain", "sphere", "domains"],
  례물: ["gift", "gifts"],
  례배: ["service", "services", "office", "church"],
  례배당: ["church"],
  로그아웃: ["logout"],
  로그인: ["login"],
  로동: ["work"],
  로봇: ["android", "robot"],
  로선: ["route"],
  로출: ["exposure"],
  로켓: ["rocket"],
  로켓트: ["rocket"],
  로터스: ["lotus"],
  로프: ["rope"],
  록색: ["green"],
  록음: ["recording"],
  론단: ["forum"],
  론리: ["logic"],
  론리학: ["logic"],
  론문: ["article"],
  론평: ["comment", "comments"],
  롤러: ["roller"],
  롤러코스터: ["rollercoaster"],
  롱구: ["basketball"],
  료금: ["fare"],
  료리: ["cooking", "dish"],
  료리사: ["chef"],
  료법: ["therapy"],
  루두: ["funnel"],
  루블: ["ruble"],
  루설: ["leak"],
  루타: ["double", "single", "triple"],
  루틴: ["routine"],
  루피: ["rupee"],
  룰러: ["ruler"],
  룰렛: ["roulette"],
  류리: ["glass"],
  류머티스학: ["rheumatology"],
  류성: ["meteor"],
  륙색: ["backpack"],
  륙지: ["land", "earth"],
  리더: ["reader"],
  리듬: ["rhythm"],
  리라: ["lira"],
  리륙: ["takeoff"],
  리면: ["back"],
  리미트: ["limits"],
  리믹스: ["remix"],
  리본: ["ribbon"],
  리뷰: ["review", "reviews"],
  리셉션: ["registration"],
  리스트: ["list", "lists"],
  리식: ["interests"],
  리알: ["rial"],
  리액션: ["reaction"],
  리얄: ["riyal"],
  리용자: ["user", "users"],
  리유: ["reason"],
  리익: ["interests"],
  리자: ["interests"],
  리코더: ["recorder"],
  리크: ["leak"],
  리포트: ["report", "reports"],
  리플: ["reply"],
  리플레이: ["replay"],
  릴리스: ["release"],
  림시직원: ["temp"],
  립방: ["cube"],
  립방체: ["cube"],
  립체: ["solids"],
  링크: ["link", "links"],
  마개: ["plug", "plugs"],
  마구간: ["stable"],
  마나트: ["manat"],
  마당: ["yard"],
  마디: ["word"],
  마력: ["spell"],
  마름모: ["rhombus"],
  마리: ["head"],
  마법: ["magic"],
  마사지: ["massage"],
  마술: ["magic"],
  마스크: ["mask", "masks"],
  마실것: ["drinks", "drink", "beverage"],
  마우스: ["mouse"],
  마을: ["village"],
  마음: ["heart", "mind"],
  마이크: ["microphone"],
  마이크로칩: ["microchip"],
  마이크로파: ["microwave"],
  마이크로폰: ["microphone"],
  마진: ["margin"],
  마차: ["carriage"],
  마천루: ["skyscraper"],
  마치: ["hammer"],
  마크: ["mark"],
  막다른길: ["close"],
  막대: ["stick", "rod", "staff"],
  막대기: ["stick", "rod", "pole", "staff"],
  막대사탕: ["lollipop"],
  막대표시: ["barcode"],
  만나기: ["meeting"],
  만날약속: ["date"],
  만년필: ["pen"],
  만두: ["dumpling"],
  만찬: ["dinner"],
  만화: ["comic", "manga"],
  말뚝: ["pile"],
  말뿌리: ["root"],
  말소: ["cancellation"],
  말솜씨: ["delivery"],
  말씀: ["word"],
  말줄임표: ["ellipsis"],
  말하기: ["speech"],
  망가: ["manga"],
  망각: ["angle"],
  망원경: ["telescope"],
  망치: ["hammer"],
  매뉴얼: ["manual"],
  매니저: ["manager"],
  매매: ["business", "transaction"],
  매점: ["kiosk"],
  매직: ["magic"],
  매체: ["media"],
  매크로: ["macro"],
  맥박: ["pulse"],
  맥주: ["beer"],
  맨션: ["apartment"],
  머그: ["mug"],
  머그잔: ["mug"],
  머그컵: ["mug"],
  머리: ["head", "hair"],
  머리받기: ["header"],
  머리카락: ["hair"],
  머리칼: ["hair"],
  머리털: ["hair"],
  머릿골: ["brain"],
  머신: ["machine"],
  먹물: ["ink"],
  먹을것: ["food"],
  먹이: ["food", "feed"],
  멀떠구니: ["crop"],
  멀티골: ["braces"],
  멈춤: ["pause"],
  메가폰: ["megaphone"],
  메노라: ["menorah"],
  메뉴: ["menu"],
  메뉴판: ["menu"],
  메달: ["medal"],
  메론: ["melon"],
  메모: ["note", "notes"],
  메모리: ["memory"],
  메모장: ["notepad"],
  메뫼: ["mountain", "mountains"],
  메서드: ["method"],
  메서드연기: ["method"],
  메소드: ["method"],
  메소드연기: ["method"],
  메시지: ["text", "message", "messages"],
  메신저: ["messenger"],
  메일: ["email"],
  메탈: ["metal"],
  메트로: ["subway"],
  메트로놈: ["metronome"],
  멜론: ["melon"],
  멤버: ["member"],
  멤버십: ["membership"],
  면도기: ["razor"],
  면도칼: ["razor"],
  면역학: ["immunology"],
  면적: ["area"],
  면허: ["license"],
  면허증: ["license"],
  멸망: ["destruction", "fall"],
  명령: ["order", "command", "charge", "orders"],
  명령어: ["command", "commands"],
  명부: ["list", "lists"],
  명세: ["details"],
  명예: ["honor"],
  모금: ["draft", "drafts"],
  모노레일: ["monorail"],
  모뉴먼트: ["monument"],
  모니터: ["monitor"],
  모니터링: ["monitoring"],
  모델: ["model"],
  모듈: ["module"],
  모드: ["mode"],
  모래상자: ["sandbox"],
  모래시계: ["hourglass"],
  모루: ["anvil"],
  모범: ["model"],
  모빌: ["mobile"],
  모사: ["copy"],
  모서리: ["corner", "corners"],
  모스크: ["mosque"],
  모습: ["design"],
  모식: ["pattern"],
  모양: ["looks", "shapes", "shape", "look"],
  모욕: ["taunt"],
  모이: ["feed"],
  모임: ["assembly"],
  모자: ["hat", "cap"],
  모자이크: ["mosaic"],
  모종삽: ["trowel"],
  모터: ["engine", "motor"],
  모터사이클: ["motorcycle"],
  모터스포츠: ["motorsports"],
  모퉁이: ["corner", "corners", "angle"],
  모판: ["bed", "beds"],
  모페드: ["moped"],
  모형: ["model", "pattern"],
  목록: ["list", "inventory", "lists"],
  목소리: ["voice"],
  목수: ["carpenter"],
  목욕: ["bath"],
  목욕실: ["bath", "bathroom"],
  목욕통: ["bathtub"],
  목자: ["cowboy"],
  목재: ["wood"],
  목적: ["end", "target", "task", "object"],
  목적어: ["object", "objects"],
  목표: ["target", "task", "vision", "goal"],
  목표물: ["landmark"],
  목화: ["boot"],
  몸짓: ["gesture"],
  몽둥이: ["club"],
  묘사: ["description"],
  무게: ["weight"],
  무기: ["arms", "arm"],
  무늬: ["design", "pattern"],
  무대: ["stage"],
  무더기: ["stack", "heap", "stacks", "pile"],
  무덤: ["grave"],
  무도회: ["ball"],
  무릎: ["laps"],
  무선: ["radio"],
  무선호출기: ["pager"],
  무승부: ["draw", "tie"],
  무식: ["dark"],
  무인기: ["drone"],
  무인항공기: ["drone"],
  무지개: ["rainbow"],
  무한: ["infinity"],
  무한대: ["infinity"],
  문법: ["grammar"],
  문법책: ["grammar"],
  문법학: ["grammar"],
  문서: ["script", "document"],
  문양: ["charge"],
  문의: ["ticket", "tickets"],
  문자: ["letter", "script", "alphabet", "character"],
  문장: ["script"],
  문제: ["task", "problem", "matter"],
  물개: ["seal"],
  물건: ["object", "objects", "things"],
  물건사기: ["shopping"],
  물결: ["wave", "waves", "ripple", "ripples"],
  물고기: ["fish"],
  물범: ["seal"],
  물질: ["matter"],
  물질대사: ["metabolism"],
  미끄럼대: ["slide", "slides"],
  미끄럼틀: ["slide", "slides"],
  미끼샤: ["blender"],
  미남: ["beauty"],
  미녀: ["beauty"],
  미디어: ["media", "press"],
  미르: ["dragon"],
  미리보기: ["preview"],
  미사일: ["rocket"],
  미생물학: ["microbiology"],
  미성년자: ["minor"],
  미소: ["smile"],
  미소년: ["beauty"],
  미술: ["art", "arts"],
  미술관: ["museum"],
  미스터리: ["mystery"],
  미인: ["beauty"],
  미친사람: ["nut"],
  믹서: ["blender"],
  민족: ["people"],
  밀기울: ["meal", "meals"],
  밀도: ["density"],
  밀정: ["spy"],
  밀크: ["milk"],
  밀크셰이크: ["shake", "milkshake"],
  밑면: ["base"],
  밑변: ["base"],
  밑줄: ["underline"],
  바게트: ["baguette"],
  바구니: ["basket"],
  바나나: ["banana"],
  바나나색: ["banana"],
  바늘: ["hand", "pointer", "hands", "needle"],
  바늘귀: ["eye", "eyes"],
  바다거북: ["turtle"],
  바닥: ["floor", "ground"],
  바닷가: ["beach"],
  바드민톤: ["badminton"],
  바람: ["wind"],
  바람개비: ["pinwheel"],
  바람자루: ["windsock"],
  바로가기: ["shortcut"],
  바른륙면체: ["cube"],
  바리: ["load"],
  바리케이드: ["barricade"],
  바벨: ["barbell"],
  바비큐: ["grill"],
  바스켓: ["basket"],
  바스켓볼: ["basketball"],
  바이너리파일: ["binary"],
  바이러스: ["virus"],
  바이오해저드: ["biohazard"],
  바지: ["pants"],
  바코드: ["barcode"],
  바퀴: ["wheel"],
  바퀴살: ["spoke"],
  바퀴의자: ["wheelchair"],
  바탕: ["ground"],
  바탕색: ["background"],
  바탕화면: ["desktop"],
  박물관: ["museum"],
  박스: ["box"],
  박자: ["beats"],
  박쥐: ["bat"],
  반경: ["radius"],
  반구: ["hemisphere"],
  반동: ["reaction"],
  반려동물: ["pet", "pets"],
  반려자: ["partner"],
  반응: ["feedback", "reaction"],
  반장: ["monitor"],
  반지: ["ring", "rings"],
  반지름: ["radius"],
  받는사람: ["receiver"],
  발가락: ["digit"],
  발뒤꿈치: ["heel"],
  발뒤축: ["heel"],
  발리볼: ["volleyball"],
  발열: ["temperature"],
  발자국: ["trail", "footprints", "footprint"],
  발차: ["departure"],
  발코니: ["balcony"],
  발포: ["shooting"],
  발표: ["release"],
  밥상: ["table"],
  밧줄: ["rope"],
  방갈로: ["bungalow"],
  방귀: ["wind"],
  방망이: ["bat"],
  방면군: ["front"],
  방문: ["call", "calls"],
  방문객: ["visitor"],
  방법: ["procedure", "method"],
  방사: ["radiation"],
  방사선학: ["radiology"],
  방송: ["broadcast"],
  방송국: ["station"],
  방송원: ["anchor"],
  방식: ["method"],
  방아쇠: ["trigger"],
  방울: ["drop", "drops"],
  방패: ["shield"],
  방학: ["holiday"],
  방향: ["directions", "direction"],
  방향결수: ["gradient"],
  방향지시등: ["indicator"],
  방호: ["security"],
  방화벽: ["firewall"],
  배경: ["background"],
  배경화면: ["desktop"],
  배관: ["pipeline"],
  배구: ["volleyball"],
  배구공: ["volleyball"],
  배낭: ["backpack"],
  배너: ["banner"],
  배달: ["delivery"],
  배달물: ["delivery"],
  배드민턴: ["badminton"],
  배럴: ["barrel"],
  배수: ["multiple"],
  배열: ["array"],
  배우: ["actors"],
  배율: ["power"],
  배지: ["badge", "badges"],
  배터리: ["battery"],
  배트: ["bat"],
  배후: ["back", "rear"],
  백그라운드: ["background"],
  백분비: ["percentage"],
  백분율: ["percentage"],
  백색: ["white"],
  백성: ["people", "subject"],
  백스페이스: ["backspace"],
  백스페이스키: ["backspace"],
  백신: ["vaccines", "vaccine"],
  백업: ["backup"],
  백인: ["white"],
  백일몽: ["daydream"],
  백판: ["whiteboard"],
  백팩: ["backpack"],
  밴드: ["band"],
  밸브: ["valve"],
  버거: ["burger"],
  버그: ["bug", "bugs"],
  버러지: ["worm"],
  버섯: ["mushroom"],
  버스: ["bus"],
  버전: ["versions"],
  버찌: ["cherry"],
  버킷: ["bucket"],
  버튼: ["key", "button", "keys", "buttons"],
  번개: ["lightning"],
  번역기: ["interpreter"],
  번호: ["number", "numbers"],
  벌금: ["fine"],
  벌레: ["bug", "bugs", "worm"],
  범례: ["legend"],
  범선: ["sailboat"],
  범위: ["area", "sphere"],
  범인: ["criminal"],
  범죄인: ["criminal"],
  범죄자: ["criminal"],
  범주: ["category"],
  범칙금: ["fine"],
  범퍼: ["bumper"],
  법률안: ["bill"],
  법선: ["normal"],
  법안: ["bill"],
  법원: ["court"],
  법인: ["person"],
  법적강권: ["capacity"],
  법전: ["code"],
  법정: ["court"],
  벙어리: ["mute"],
  베개: ["pillow"],
  베이비: ["baby"],
  베이스볼: ["baseball"],
  베이커리: ["bakery"],
  베타: ["beta"],
  베틀: ["loom"],
  벡터: ["vector"],
  벤토: ["bento"],
  벨트: ["belt"],
  벼락: ["lightning"],
  벼랑: ["cliff"],
  벽난로: ["fireplace"],
  벽돌: ["brick"],
  벽지: ["wallpaper"],
  변기: ["toilet"],
  변소: ["toilet"],
  변속기: ["gearbox"],
  변수: ["variable", "variables"],
  변제: ["payment", "payments"],
  변형력: ["stress"],
  변화: ["transition", "change", "changes", "transitions"],
  별명: ["alias"],
  별장: ["cottage", "villa"],
  별표: ["star", "asterisk", "stars"],
  병독: ["virus"],
  병동: ["ward"],
  병력: ["history"],
  병법: ["strategy"],
  병실: ["ward"],
  병역: ["service", "services"],
  병원: ["hospital"],
  병인: ["patient"],
  병졸: ["private"],
  보고: ["report", "reports"],
  보고서: ["report", "reports"],
  보관소: ["archive"],
  보금자리: ["nest"],
  보닛: ["hood"],
  보도: ["news", "press", "coverage"],
  보드: ["board"],
  보모: ["nurse"],
  보물: ["treasure"],
  보배: ["treasure"],
  보살: ["assist"],
  보석: ["gem", "stone"],
  보안: ["security"],
  보증: ["security", "guarantee"],
  보증금: ["deposit"],
  보트: ["boat"],
  보표: ["staff"],
  보행: ["walking"],
  보행자: ["pedestrian"],
  보호: ["security"],
  보호물: ["shield"],
  보호자: ["shield", "parent", "guardian"],
  복무: ["service", "services"],
  복습: ["review", "reviews"],
  복싱: ["boxing"],
  복음: ["word"],
  복장: ["apparel"],
  복제: ["duplicate"],
  본문: ["text"],
  본보기: ["model"],
  본원: ["source"],
  본체: ["body"],
  볼넷: ["walk"],
  볼런티어: ["volunteer"],
  볼륨: ["volume"],
  볼링: ["bowling"],
  볼트: ["bolt"],
  볼트미터: ["voltmeter"],
  볼펜: ["pen"],
  봉사: ["service", "services"],
  봉사기: ["server"],
  봉지: ["bag", "bags"],
  봉투: ["bag", "envelope", "bags"],
  부동산: ["land"],
  부두: ["dock"],
  부름: ["call", "calls"],
  부리: ["bill"],
  부모: ["parent"],
  부모님: ["parent"],
  부문: ["category"],
  부분: ["share", "area", "slice", "component"],
  부분집합: ["subset"],
  부상: ["injury", "wounds"],
  부서: ["department"],
  부수: ["radical"],
  부아: ["lungs"],
  부엉이: ["owl"],
  부엌: ["kitchen"],
  부이: ["buoy"],
  부인과: ["gynecology"],
  부잔교: ["landing"],
  부조화: ["discord"],
  부지깽이: ["poker"],
  부채: ["fan"],
  부처: ["ministry"],
  부탁: ["request"],
  부표: ["buoy"],
  부호: ["code", "sign", "signs", "symbols"],
  북마크: ["bookmark", "bookmarks"],
  북방: ["north"],
  북쪽: ["north"],
  북채: ["drumstick"],
  분광: ["spectrum"],
  분국: ["branch"],
  분기: ["quarter"],
  분동: ["weight"],
  분량: ["quantity"],
  분류: ["category"],
  분리: ["crisis"],
  분만: ["delivery"],
  분수: ["fountain"],
  분야: ["area", "sphere"],
  분위기: ["mood"],
  분유: ["formula"],
  분의: ["third", "quarter"],
  분쟁: ["conflict"],
  불길: ["flame"],
  불꽃: ["spark", "flame"],
  불도저: ["bulldozer"],
  불시착: ["crash"],
  불쏘시개: ["kindling"],
  불알: ["ball"],
  불협화음: ["discord"],
  붕괴: ["collapse"],
  붕대: ["bandage"],
  뷰파인더: ["viewfinder"],
  브랜디: ["brandy"],
  브러시: ["brush"],
  브런치: ["brunch"],
  브로콜리: ["broccoli"],
  브리지: ["bridge"],
  블라인드: ["blinds", "blind"],
  블랙베리: ["blackberry"],
  블렌더: ["blender"],
  블로거: ["blogger"],
  블록: ["block", "blocks"],
  비난: ["charge"],
  비뇨기과: ["urology"],
  비누: ["soap"],
  비늘: ["scale"],
  비니: ["beanie"],
  비닐: ["vinyl"],
  비단뱀: ["python"],
  비디오: ["video"],
  비디오카메라: ["camera"],
  비디오테이프: ["videotape"],
  비례: ["proportions"],
  비루스: ["virus"],
  비률: ["rate"],
  비밀번호: ["password"],
  비번: ["password"],
  비상사태: ["emergency"],
  비숍: ["bishop"],
  비스킷: ["cookie"],
  비율: ["rate", "ratio"],
  비자: ["visa"],
  비축: ["stock"],
  비커: ["beaker"],
  비탈도: ["gradient"],
  비트: ["bit"],
  비트코인: ["bitcoin"],
  비틀기: ["wrench"],
  비평: ["feedback"],
  비행: ["flight", "flights"],
  비행기: ["airplane", "plane"],
  비행기구름: ["contrails"],
  비행장: ["airports", "airport"],
  빈병: ["empty"],
  빈지문: ["shutter"],
  빈칸: ["blank"],
  빌딩: ["building", "buildings"],
  빌라: ["villa"],
  빗금: ["slash"],
  빗자루: ["broom"],
  빙산: ["iceberg"],
  빛줄기: ["beam"],
  빠르기: ["speed"],
  빤스: ["pants"],
  빨간색: ["red"],
  빨강: ["red"],
  빨갱이: ["red"],
  빨래: ["laundry"],
  빨래건조기: ["dryer"],
  빨랫감: ["laundry"],
  빵집: ["bakery"],
  뻐스: ["bus"],
  뼈다귀: ["bone", "bones"],
  뼈대: ["skeleton"],
  뿌리: ["root"],
  삐삐: ["pager"],
  삥샹: ["refrigerator"],
  사거리: ["intersection"],
  사건: ["event", "case", "cases"],
  사격: ["shooting"],
  사과: ["apple"],
  사구: ["walk"],
  사내: ["man"],
  사내아이: ["boy"],
  사냥: ["hunt"],
  사냥감: ["game", "games"],
  사다리: ["ladder"],
  사닥다리: ["ladder"],
  사람: ["person", "man", "people", "human"],
  사람들: ["people", "men"],
  사랑: ["love"],
  사령기: ["flag"],
  사령부: ["base"],
  사료: ["feed"],
  사루: ["hourglass"],
  사루계: ["hourglass"],
  사립탐정: ["detective"],
  사무소: ["office"],
  사무실: ["office"],
  사문: ["ripple", "ripples"],
  사발: ["bowl"],
  사분의일: ["quarter"],
  사생활: ["privacy"],
  사슴: ["deer"],
  사실: ["fact"],
  사업: ["business", "enterprise"],
  사역마: ["familiar"],
  사용자: ["user", "users"],
  사용자명: ["login"],
  사용자이름: ["login"],
  사우나: ["sauna"],
  사원: ["temple"],
  사이드바: ["sidebar"],
  사이렌: ["siren"],
  사이즈: ["size"],
  사이클론: ["cyclone"],
  사이클링히트: ["cycle"],
  사인: ["signature", "sine", "individual"],
  사자: ["messenger", "deceased"],
  사장: ["sandbox"],
  사전: ["dictionary"],
  사증: ["visa"],
  사진: ["picture"],
  사진기: ["camera"],
  사진술: ["photography"],
  사진첩: ["album"],
  사찰: ["temple"],
  사커: ["soccer"],
  사탕: ["candy"],
  사파리: ["safari"],
  사학: ["history"],
  삭과: ["capsule"],
  삭제: ["cancellation"],
  산사태: ["landslide"],
  산소: ["oxygen"],
  산소원자: ["oxygen"],
  산책: ["walk", "hike"],
  산판: ["abacus"],
  살아있음: ["living"],
  삼각: ["triangle", "triangles"],
  삼각김밥: ["onigiri"],
  삼각주: ["delta"],
  삼각형: ["triangle", "triangles"],
  삼림: ["forest"],
  삼분의일: ["third"],
  삼승: ["cube"],
  삼지창: ["trident"],
  상관관계: ["function", "functions"],
  상륙: ["landing"],
  상세: ["details"],
  상완골: ["humerus"],
  상자: ["box", "case", "cases"],
  상점: ["shop"],
  상징: ["symbols"],
  상처: ["wounds"],
  상태: ["status", "conditions"],
  상패: ["medal"],
  상표: ["trademark"],
  상품: ["product"],
  상해: ["injury"],
  새끼: ["baby"],
  새로고침: ["refresh"],
  새우: ["shrimp"],
  새장: ["birdhouse"],
  새집: ["nest", "birdhouse"],
  색깔: ["color", "colors"],
  색동다리: ["rainbow"],
  색안경: ["sunglasses"],
  색인: ["index"],
  색종이조각: ["confetti"],
  샌드박스: ["sandbox"],
  샌드위치: ["sandwich"],
  샐러드: ["salad"],
  샘플: ["template", "sample"],
  생계: ["living"],
  생명: ["life"],
  생산: ["production"],
  생산력: ["capacity"],
  생선: ["fish"],
  생성물: ["product"],
  생장: ["growth"],
  생존: ["living"],
  생쥐: ["mouse"],
  생포: ["capture"],
  생활: ["life"],
  생활방식: ["living"],
  생활양식: ["living"],
  샤워: ["shower", "showers"],
  샤워기: ["shower", "showers"],
  샴페인: ["champagne"],
  서고: ["library"],
  서랍: ["drawer"],
  서랍장: ["chest"],
  서류: ["document"],
  서류가방: ["briefcase"],
  서류철: ["file", "folder", "files", "folders"],
  서명: ["signature", "title"],
  서모스탯: ["thermostat"],
  서민: ["people"],
  서버: ["server"],
  서브우퍼: ["subwoofer"],
  서비스: ["service", "services"],
  서술: ["description"],
  서양장기: ["chess"],
  서쪽: ["west"],
  서체: ["font"],
  서커스: ["circus"],
  서클: ["circle", "circles"],
  서표: ["bookmark", "bookmarks"],
  서핑: ["surfing"],
  석감: ["soap"],
  석방: ["release"],
  석유: ["oil"],
  섞다: ["blend"],
  선글라스: ["sunglasses"],
  선로: ["railway", "rail"],
  선물: ["gift", "gifts"],
  선박: ["ship"],
  선반: ["shelf", "rack"],
  선생: ["teacher"],
  선생님: ["teacher"],
  선수: ["player", "bow"],
  선실: ["cabin"],
  선율: ["tune"],
  선인장: ["cactus"],
  선조: ["people", "filament"],
  선택: ["selection", "options", "option", "preferences"],
  선택권: ["options", "option"],
  선택지: ["options", "option", "choice"],
  선풍기: ["fan"],
  설계: ["design"],
  설계도: ["blueprint", "plan"],
  설계자: ["planner"],
  설립: ["foundation"],
  설명: ["description"],
  설문지: ["questionnaire"],
  설백: ["snow"],
  설비: ["plant"],
  설상차: ["snowmobile"],
  설치: ["foundation"],
  설치류: ["rodent"],
  설편: ["snowflake"],
  설화: ["snowflake"],
  섬광: ["flash"],
  섬네일: ["thumbnail", "thumbnails"],
  성격: ["character"],
  성경: ["bible"],
  성곽: ["castle"],
  성교: ["action", "union", "actions"],
  성냥: ["match", "matchstick"],
  성당: ["church"],
  성량: ["volume"],
  성모: ["initial"],
  성벽: ["wall"],
  성별: ["gender"],
  성상: ["icons"],
  성새: ["fortress"],
  성서: ["bible"],
  성인: ["adult"],
  성장: ["growth"],
  성적: ["mark", "score", "grade"],
  성질: ["nature"],
  성화: ["icons"],
  세계: ["world"],
  세금: ["tax"],
  세단기: ["shredder"],
  세대: ["generation"],
  세력: ["power"],
  세로단: ["columns", "column"],
  세리프: ["serif"],
  세모: ["triangle", "triangles"],
  세부: ["details"],
  세이렌: ["siren"],
  세일: ["sale"],
  세제곱: ["cube"],
  세탁: ["laundry"],
  세탁물: ["laundry"],
  세탁소: ["laundry"],
  세탁실: ["laundry"],
  세트: ["set"],
  세포: ["cell", "cells"],
  섹션: ["section"],
  센서: ["sensor", "sensors"],
  센트: ["cent"],
  센트반: ["bit"],
  셀카: ["selfie"],
  셀프카메라: ["selfie"],
  셀피: ["selfie"],
  셈판: ["abacus"],
  셔츠: ["shirt"],
  셔터: ["shutter"],
  셔틀: ["shuttle"],
  셰이크: ["shake"],
  셰켈: ["shekel"],
  셰프: ["chef"],
  소고기: ["beef"],
  소굴: ["hangout"],
  소금: ["salt"],
  소나기: ["shower", "showers"],
  소나무: ["pine"],
  소녀: ["girl"],
  소년: ["boy"],
  소다: ["soda"],
  소다수: ["soda"],
  소리: ["sound", "voice", "ring", "rings"],
  소묘: ["sketch"],
  소문: ["news", "talk"],
  소바: ["soba"],
  소송: ["action", "actions"],
  소시지: ["sausage"],
  소식: ["text", "message", "news", "messages"],
  소옥: ["cabin"],
  소원: ["wish"],
  소유권: ["title"],
  소음: ["noise"],
  소제부: ["cleaner"],
  소책자: ["booklet"],
  소케트: ["socket"],
  소켓: ["socket"],
  소통: ["communication"],
  소파: ["couch", "sofa"],
  소포: ["packet"],
  소풍: ["picnic"],
  속도: ["speed"],
  속도계: ["speedometer"],
  속력: ["speed"],
  속성: ["attributes"],
  손가락: ["finger", "digit", "fingers"],
  손가방: ["handbag"],
  손님: ["visitor", "customer"],
  손목: ["wrist"],
  손바닥: ["palm"],
  손상: ["damage"],
  손실: ["loss", "damage", "toll"],
  손잡이: ["handle"],
  손전등: ["flashlight"],
  손해: ["damage"],
  솔방울: ["cone"],
  솜털: ["down"],
  송구: ["handball"],
  송장: ["invoice", "bill"],
  쇄자갑: ["mail", "mails"],
  쇠고기: ["beef"],
  쇠스랑: ["fork"],
  쇼콜라: ["chocolate"],
  쇼콜라색: ["chocolate"],
  쇼파: ["sofa"],
  쇼핑: ["shopping"],
  쇼핑센터: ["mall"],
  수건: ["towel"],
  수다: ["chat", "chats"],
  수단: ["route", "procedure"],
  수대: ["zodiac"],
  수도꼭지: ["faucet"],
  수량: ["number", "numbers", "quantity"],
  수레: ["cart"],
  수렵: ["hunt"],
  수렵물: ["game", "games"],
  수로: ["channels", "channel"],
  수리: ["repair"],
  수면: ["sleep"],
  수벌: ["drone"],
  수사: ["number", "numbers"],
  수상기: ["television"],
  수색: ["search", "detection"],
  수송: ["transportation"],
  수송선: ["ferry"],
  수수께끼: ["puzzle"],
  수술: ["operations"],
  수식: ["expression"],
  수식어: ["attributes"],
  수신기: ["receiver"],
  수신인: ["receiver"],
  수업: ["class", "lesson"],
  수염: ["moustache"],
  수영: ["swimming"],
  수용력: ["capacity"],
  수위표: ["watermark"],
  수입: ["import"],
  수입품: ["import"],
  수정: ["crystal"],
  수정체: ["lens"],
  수준: ["level"],
  수집: ["collections"],
  수첩: ["notebook"],
  수출: ["export"],
  수출품: ["export"],
  수취인: ["receiver"],
  수캐: ["dog"],
  수컷: ["male"],
  수탁물: ["charge"],
  수판: ["abacus"],
  수평: ["level"],
  수평선: ["horizon"],
  수풀: ["wood"],
  수프: ["soup"],
  수하물: ["luggage"],
  수형도: ["tree", "trees"],
  수화: ["sign", "signs"],
  수화기: ["receiver"],
  수확: ["crop"],
  숙제: ["assignment"],
  순간: ["time", "times", "instant"],
  순서: ["order", "orders"],
  순위: ["rating", "ranking"],
  순환: ["rotation"],
  숟가락: ["spoon"],
  술래잡기: ["tag", "tags"],
  술집: ["bar", "bars"],
  숫벌: ["drone"],
  숫양: ["ram"],
  숫자: ["number", "numbers", "digit"],
  숲속공터: ["lawn"],
  슈즈: ["shoe"],
  슈트케이스: ["suitcase"],
  스냅샷: ["snapshot"],
  스노모바일: ["snowmobile"],
  스노보드: ["snowboard"],
  스노우보드: ["snowboard"],
  스노우화면: ["snow"],
  스니커즈: ["sneaker"],
  스마일: ["smile"],
  스마일리: ["smiley"],
  스마트폰: ["smartphone"],
  스샷: ["screenshot"],
  스위치: ["switch"],
  스캐너: ["scanner"],
  스케이트보드: ["skateboard"],
  스케줄: ["schedule"],
  스케치: ["sketch"],
  스켈레톤: ["skeleton"],
  스코어: ["score"],
  스코어보드: ["scoreboard"],
  스쿠터: ["scooter"],
  스크롤: ["scroll"],
  스크루드라이버: ["screwdriver"],
  스크린: ["screen"],
  스크린샷: ["screenshot"],
  스크린세이버: ["screensaver"],
  스크립트: ["script"],
  스키: ["ski"],
  스키마: ["schema"],
  스타: ["star", "stars"],
  스타디움: ["stadium"],
  스타일: ["style"],
  스타일러스: ["stylus"],
  스태프: ["staff"],
  스택: ["stack", "stacks"],
  스탠더드: ["standard"],
  스탠드: ["stand"],
  스테이지: ["stage"],
  스토아: ["shop"],
  스톤: ["stone"],
  스툴: ["stool"],
  스튜디오: ["studio"],
  스트라이크존: ["zone"],
  스트레스: ["stress"],
  스트레이트: ["straight"],
  스트레칭: ["stretch", "stretching"],
  스트리퍼: ["stripper"],
  스트림: ["stream"],
  스티커: ["sticker", "stickers"],
  스파이: ["spy"],
  스파크: ["spark"],
  스팸: ["spam"],
  스팸메일: ["spam"],
  스페셜: ["special"],
  스페이드: ["spades"],
  스페이스: ["space", "spaces"],
  스펙트럼: ["spectrum"],
  스포츠: ["sports", "sport"],
  스푼: ["spoon"],
  스풀: ["spool"],
  스프레드시트: ["spreadsheet"],
  스프레이: ["spray"],
  스프린트: ["sprint"],
  스프링클러: ["sprinkler"],
  스플릿: ["split"],
  스피커: ["speaker"],
  슬라이더: ["sliders"],
  슬라이드: ["slide", "slides"],
  슬라이딩: ["slide", "slides"],
  슬라이스: ["slice"],
  슬래시: ["slash"],
  습관: ["custom"],
  습기: ["humidity"],
  습도: ["humidity"],
  승강기: ["lift"],
  승강장: ["platform"],
  승객: ["fare"],
  승수: ["multiplier"],
  승인: ["approval", "recognition"],
  승합차: ["van"],
  시각: ["time", "angle", "times", "vision"],
  시간: ["time", "hour", "times", "hours"],
  시간표: ["schedule"],
  시계: ["clock", "watch"],
  시골집: ["cottage"],
  시그널: ["signal"],
  시그마: ["sigma"],
  시나고그: ["synagogue"],
  시내: ["stream", "city"],
  시대: ["time", "times"],
  시럽: ["syrup"],
  시력: ["vision"],
  시상: ["award"],
  시설: ["plant"],
  시야: ["view"],
  시인: ["bard"],
  시작: ["start", "beginning"],
  시점: ["angle"],
  시정: ["visibility"],
  시제품: ["approval"],
  시트: ["seat", "sheets", "sheet"],
  시트러스: ["citrus"],
  시프트: ["shift"],
  시프트키: ["shift"],
  시합: ["game", "match", "games"],
  시험: ["test"],
  식기세척기: ["dishwasher"],
  식단표: ["menu"],
  식당: ["restaurant"],
  식량: ["food"],
  식물: ["plant"],
  식물유: ["oil"],
  식별: ["identification"],
  식사: ["meal", "meals", "dish"],
  식판: ["tray"],
  식품: ["food"],
  식현상: ["eclipse"],
  신경학: ["neurology"],
  신뢰: ["credit", "credits"],
  신문: ["newspaper"],
  신문가판대: ["newsstand"],
  신문지: ["newspaper"],
  신문판매대: ["newsstand"],
  신민: ["subject"],
  신발: ["shoe"],
  신분: ["status"],
  신분증: ["identification"],
  신비: ["mystery"],
  신용: ["credit", "credits"],
  신용도: ["credit", "credits"],
  신진대사: ["metabolism"],
  신청: ["applications"],
  신청서: ["applications"],
  신체: ["body"],
  신하: ["people", "subject"],
  신호: ["signal", "sign", "signs"],
  실력자: ["wheel"],
  실린더: ["cylinder"],
  실수: ["error", "errors"],
  실재: ["reality"],
  실제: ["fact"],
  실책: ["error", "errors"],
  실패: ["reel", "spool"],
  실험: ["experiment"],
  싫어요: ["dislike"],
  심리: ["psychology"],
  심리학: ["psychology"],
  심박: ["heartbeat"],
  심벌: ["symbols"],
  심상: ["image", "images"],
  심성: ["mind"],
  심장: ["heart"],
  심장박동조율기: ["pacemaker"],
  심장병학: ["cardiology"],
  십이궁: ["zodiac"],
  십이성좌: ["zodiac"],
  십자: ["cross"],
  십자가: ["cross"],
  십자말: ["crossword"],
  십자선: ["crosshair"],
  십자성호: ["cross"],
  십진법: ["decimal", "decimals"],
  싱글: ["single"],
  쌍안경: ["binoculars"],
  썬글라스: ["sunglasses"],
  썰매타기: ["sledding"],
  쓰기: ["writing"],
  쓰나미: ["tsunami"],
  쓰레기: ["trash"],
  쓰레기통: ["bin"],
  아기: ["baby"],
  아나운서: ["anchor"],
  아니메: ["animation"],
  아다: ["cherry"],
  아령: ["dumbbell"],
  아름다움: ["beauty"],
  아바타: ["avatar"],
  아보카도: ["avocado"],
  아빠트: ["apartment"],
  아이: ["child", "boy"],
  아이덴티티: ["identity"],
  아이스: ["ice"],
  아이스캔디: ["popsicle"],
  아이스크림: ["ice"],
  아이콘: ["icons"],
  아이템: ["item", "items"],
  아치: ["arch"],
  아침: ["breakfast"],
  아침놀: ["sunrise"],
  아침밥: ["breakfast"],
  아침식사: ["breakfast"],
  아카이브: ["archive"],
  아케이드: ["arcade"],
  아톰: ["atom"],
  아트: ["art", "arts"],
  아틀리에: ["studio"],
  아파트: ["apartment"],
  아프가니: ["afghani"],
  악곡: ["tune"],
  악구: ["phrases"],
  악단: ["band"],
  악보: ["music", "score"],
  악수: ["handshake"],
  안개: ["fog", "mist"],
  안경다리: ["temple"],
  안과: ["ophthalmology"],
  안과학: ["ophthalmology"],
  안내: ["information"],
  안내서: ["guide", "manual", "guides"],
  안내인: ["guide", "guides"],
  안녕: ["peace"],
  안드로이드: ["android"],
  안뜰: ["court"],
  안락의자: ["armchair"],
  안마: ["massage"],
  안마당: ["court"],
  안면: ["face"],
  안전: ["security", "safety"],
  안전성: ["safety"],
  안테나: ["aerial"],
  알람: ["alarm"],
  알람시계: ["alarm"],
  알레르기: ["allergy"],
  알림: ["news"],
  알뿌리: ["bulb"],
  알약: ["pill", "pills"],
  알코올: ["alcohol"],
  알콜: ["alcohol"],
  알파: ["alpha"],
  알파벳: ["alphabet"],
  암나사: ["nut"],
  암소: ["cow"],
  암컷: ["female"],
  암호: ["code", "password"],
  암호화: ["encryption"],
  암흑: ["dark"],
  압도적인승리: ["landslide"],
  압력: ["pressure", "stress"],
  압박: ["stress"],
  앙케트: ["questionnaire"],
  앙크: ["ankh"],
  앞치마: ["apron"],
  애구: ["gap"],
  애널리틱스: ["analytics"],
  애니메이션: ["animation"],
  애스터리스크: ["star", "asterisk", "stars"],
  애완동물: ["pet", "pets"],
  애인: ["flame", "partner"],
  애정: ["love"],
  애플리케이션: ["app", "apps", "applications"],
  액션: ["action", "actions"],
  액수: ["sum"],
  액체: ["liquid"],
  액티비티: ["activity"],
  앨범: ["album"],
  앰뷸런스: ["ambulance"],
  앵커: ["anchor"],
  야구: ["baseball"],
  야구공: ["baseball"],
  야드: ["yard"],
  야영객: ["camper"],
  약간: ["bit"],
  약국: ["pharmacy"],
  약력: ["profile"],
  약리학: ["pharmacy"],
  약방: ["pharmacy"],
  약속: ["word"],
  약재: ["medicine"],
  약제사: ["pharmacy"],
  약제학: ["pharmacy"],
  약주: ["drinks", "drink"],
  약학: ["pharmacy"],
  약협: ["shell"],
  양궁: ["archery"],
  양동이: ["bucket"],
  양말: ["sock"],
  양산: ["parasol"],
  양상: ["aspect"],
  양식: ["pattern"],
  양초: ["candle"],
  양친: ["people"],
  얘기: ["conversation"],
  어구: ["phrases"],
  어근: ["root"],
  어도비: ["adobe"],
  어둠: ["dark"],
  어드민: ["admin"],
  어류: ["fish"],
  어른: ["adult"],
  어린이: ["child", "kid", "kids"],
  어버이: ["parent"],
  어스름: ["twilight"],
  어시스트: ["assist"],
  어어드: ["earth", "ground"],
  어업: ["fishing"],
  어워드: ["award"],
  어의: ["definition"],
  어족: ["family"],
  어카운트: ["account", "accounts"],
  어획물: ["game", "games"],
  어휘: ["vocabulary"],
  어휘력: ["vocabulary"],
  어휘집: ["vocabulary"],
  언론: ["media"],
  언어: ["language", "languages"],
  언제: ["dam"],
  얼굴: ["face"],
  얼음: ["ice"],
  엄지: ["thumbs", "thumb"],
  엄지손가락: ["thumbs", "thumb"],
  엄지손톱: ["thumbnail", "thumbnails"],
  업그레이드: ["upgrade"],
  업데이트: ["update", "updates"],
  업로드: ["upload"],
  업무: ["business"],
  에너지: ["energy"],
  에네르기: ["energy"],
  에디터: ["editor"],
  에러: ["error", "errors"],
  에모지: ["emoji"],
  에스컬레이터: ["escalator"],
  에일리언: ["alien", "aliens"],
  에타: ["eta"],
  엔지니어링: ["engineering"],
  엔진: ["engine", "motor"],
  엘리베이터: ["lift"],
  여객: ["fare"],
  여과기: ["filter", "filters"],
  여관: ["hotel", "hotels"],
  여권: ["passport"],
  여론조사: ["poll"],
  여배우: ["actors"],
  여백: ["blank", "margin"],
  여성: ["woman", "female"],
  여왕: ["queen"],
  여우: ["actors"],
  여유: ["room", "rooms"],
  여인: ["woman"],
  여자: ["woman", "broad", "girl"],
  여자아이: ["girl"],
  여정: ["trips", "trip"],
  여행: ["travel", "trips", "trip", "tour"],
  여행가방: ["suitcase"],
  여행가이드: ["guide", "guides"],
  역기: ["barbell"],
  역량: ["power", "capacity"],
  역법: ["calendar", "calendars"],
  역사: ["history"],
  역사선: ["backslash"],
  역슬래시: ["backslash"],
  연결: ["link", "connection", "links"],
  연구: ["research"],
  연극: ["play", "drama"],
  연기: ["smoke"],
  연기자: ["actors"],
  연단: ["platform"],
  연락: ["contact", "contacts"],
  연락선: ["ferry"],
  연료: ["fuel"],
  연맹: ["union"],
  연무: ["haze"],
  연사: ["speaker"],
  연설: ["address", "speech"],
  연설자: ["speaker"],
  연습: ["exercise"],
  연습장: ["sandbox"],
  연와: ["brick"],
  연월일: ["date"],
  연의: ["ripple", "ripples"],
  연인: ["flame", "love"],
  연주: ["performance"],
  연초: ["cigarette"],
  연필: ["pencil"],
  열쇠: ["key", "keys"],
  열쇠구멍: ["keyhole"],
  열쇠글: ["password"],
  열차: ["train"],
  염기: ["base"],
  염매: ["sale"],
  염소: ["chlorine"],
  염오: ["dislike"],
  영사기: ["projector"],
  영상: ["video", "image", "images"],
  영수증: ["receipt"],
  영양: ["nutrition"],
  영역: ["area", "domain", "sphere", "domains"],
  영향: ["effects"],
  영혼: ["ghost"],
  영화: ["picture", "movie", "movies", "cinema"],
  영화관: ["cinema"],
  영화산업: ["cinema"],
  옆구리: ["side", "sides"],
  옆얼굴: ["profile"],
  예고편: ["trailer"],
  예금: ["deposit"],
  예물: ["gift", "gifts"],
  예방: ["prevention"],
  예배: ["service", "services", "office", "church"],
  예배당: ["church"],
  예비지식: ["background"],
  예술: ["art", "arts"],
  예약: ["booking"],
  예언: ["prediction"],
  예측: ["prediction"],
  오각별: ["pentagram"],
  오각성: ["pentagram"],
  오각형: ["pentagon"],
  오늘: ["today"],
  오니기리: ["onigiri"],
  오두막: ["cottage", "cabin"],
  오두막집: ["cottage", "cabin"],
  오디오: ["audio"],
  오렌지: ["orange"],
  오렌지나무: ["orange"],
  오렌지색: ["orange"],
  오류: ["error", "errors"],
  오른쪽: ["rights"],
  오리엔테이션: ["orientation"],
  오망성: ["pentagram"],
  오메가: ["omega"],
  오물: ["trash"],
  오반: ["lunch"],
  오브젝트: ["object", "objects"],
  오븐: ["oven"],
  오솔길: ["trail"],
  오이: ["cucumber"],
  오차: ["error", "errors"],
  오코노미야키: ["okonomiyaki"],
  오타쿠: ["nerd"],
  오토메이션: ["automation"],
  오토바이: ["motorcycle"],
  오페라: ["opera"],
  오피스: ["office"],
  오후: ["afternoon"],
  옥션: ["auction"],
  옥편: ["dictionary"],
  온도: ["temperature"],
  온도계: ["thermometer"],
  온도조절기: ["thermostat"],
  온센: ["onsen"],
  온천: ["onsen"],
  올리기: ["upload"],
  올빼미: ["owl"],
  옵션: ["options", "option"],
  와드: ["ward"],
  와우: ["snail"],
  와이셔츠: ["shirt"],
  와인: ["wine"],
  완구: ["toys", "toy"],
  완롱물: ["toys", "toy"],
  왕관: ["crown"],
  왕비: ["queen"],
  왕후: ["queen"],
  외계인: ["alien", "aliens"],
  외관: ["looks", "look"],
  외국인: ["alien", "aliens"],
  외발자전거: ["unicycle"],
  외침: ["call", "exclamation", "calls", "cry"],
  외투: ["coat"],
  외형: ["looks", "look"],
  외환: ["exchange"],
  요가: ["yoga"],
  요골: ["radius"],
  요구: ["request"],
  요금: ["charge", "fare"],
  요리: ["cooking", "dish"],
  요리사: ["chef"],
  요망: ["request"],
  요법: ["therapy"],
  요부: ["siren"],
  요새: ["fort", "fortress"],
  요소: ["element"],
  요술: ["magic"],
  요약: ["summary"],
  욕실: ["bath", "bathroom"],
  욕조: ["bath", "bathtub"],
  용기: ["container"],
  용량: ["capacity"],
  용어: ["language", "vocabulary", "languages"],
  용역: ["service", "services"],
  용지: ["forms", "form"],
  우동: ["udon"],
  우등불: ["campfire"],
  우리: ["cage"],
  우박: ["hail"],
  우산: ["umbrella"],
  우상: ["icons"],
  우선: ["priority", "preferences"],
  우선권: ["priority"],
  우유: ["milk"],
  우육: ["beef"],
  우익: ["rights"],
  우주: ["space", "world", "spaces", "universe"],
  우주인: ["alien", "aliens"],
  우편: ["mail", "post", "mails"],
  운동: ["sports", "motion", "exercise", "sport"],
  운동화: ["sneaker"],
  운반: ["transportation"],
  운송: ["transportation"],
  운수: ["transportation"],
  운영자: ["admin"],
  운임: ["fare"],
  운전: ["driving"],
  울림: ["ring", "rings"],
  울안: ["yard"],
  울음: ["call", "calls", "cry"],
  울타리: ["fence"],
  움찔함: ["start"],
  웃음: ["laugh"],
  웃음소리: ["laugh"],
  워치: ["watch"],
  워크벤치: ["workbench"],
  워크스테이션: ["workstation"],
  워크스페이스: ["workspace", "workspaces"],
  워크플로: ["workflow"],
  워터마크: ["watermark"],
  워터펌프플라이어: ["wrench"],
  원고: ["columns", "column"],
  원기둥: ["cylinder"],
  원룸: ["studio"],
  원반: ["disk", "discuss"],
  원뿔: ["cone"],
  원뿔세포: ["cone"],
  원소: ["element"],
  원인: ["origin", "reason"],
  원자: ["atom"],
  원조: ["help", "support"],
  원주민: ["native"],
  원주필: ["pen"],
  원천: ["source"],
  원추세포: ["cone"],
  원통: ["cylinder"],
  원피스: ["dress"],
  원호: ["arc", "arcs"],
  원환면: ["torus"],
  월간: ["month"],
  월일: ["date"],
  웹카메라: ["webcam"],
  웹캠: ["webcam"],
  위기: ["crisis"],
  위도: ["latitude"],
  위상수학: ["topology"],
  위선: ["latitude"],
  위성: ["moon", "satellite", "planet"],
  위성방송: ["satellite"],
  위안: ["yuan"],
  위원회: ["board"],
  위장병학: ["gastroenterology"],
  위치: ["location", "position", "places", "place"],
  위팔뼈: ["humerus"],
  위험: ["threat"],
  위협: ["threat"],
  윈도: ["window", "windows"],
  윙크: ["wink"],
  유동체: ["fluid"],
  유령: ["ghost"],
  유로: ["euro"],
  유로센트: ["cent"],
  유리: ["glass"],
  유명인: ["star", "stars"],
  유모: ["nurse"],
  유모차: ["stroller"],
  유성: ["planet", "meteor"],
  유아: ["baby"],
  유안: ["yuan"],
  유저: ["user", "users"],
  유전학: ["genetics"],
  유즙: ["milk"],
  유체: ["fluid"],
  유행: ["trend"],
  유형: ["type", "transportation"],
  육각형: ["hexagon", "hexagons"],
  육지: ["land", "earth"],
  윤곽: ["profile"],
  융자: ["credit", "credits"],
  융합: ["integration"],
  은막: ["screen"],
  은하: ["galaxy"],
  은하계: ["galaxy"],
  은행: ["bank"],
  은행권: ["banknote"],
  음계: ["scale"],
  음량: ["volume"],
  음료: ["drinks", "drink", "beverage"],
  음료수: ["drinks", "drink", "beverage"],
  음모: ["plot"],
  음반: ["record", "disk"],
  음성: ["voice"],
  음성사서함: ["voicemail"],
  음소문자: ["alphabet"],
  음식: ["food"],
  음식점: ["restaurant"],
  음악: ["music"],
  음역: ["range"],
  음영: ["shadow"],
  음유시인: ["bard"],
  음자리표: ["clef"],
  음폭: ["range"],
  음표: ["note", "notes"],
  응달: ["shadow"],
  응답: ["answer"],
  응용: ["applications"],
  의도: ["design"],
  의뢰: ["request"],
  의류: ["apparel"],
  의무: ["charge"],
  의미: ["sense"],
  의복: ["dress", "apparel", "clothes"],
  의사: ["medicine"],
  의사소통: ["communication"],
  의사일정: ["agenda"],
  의식: ["office"],
  의용병: ["volunteer"],
  의원: ["house", "hospital", "clinic", "houses"],
  의자: ["chair"],
  의장: ["speaker"],
  의정서: ["protocol"],
  의제: ["agenda"],
  의학: ["medicine"],
  이국인: ["alien", "aliens"],
  이동: ["transfer"],
  이두근: ["biceps"],
  이등병: ["private"],
  이륙: ["takeoff"],
  이메일: ["email"],
  이면: ["back"],
  이모지: ["emoji"],
  이모티콘: ["emoticon"],
  이물: ["bow"],
  이미지: ["image", "images"],
  이벤트: ["event"],
  이병: ["private"],
  이불: ["blanket"],
  이빨: ["tooth"],
  이사: ["move"],
  이삭: ["ear"],
  이상형: ["type"],
  이성: ["reason"],
  이슬: ["dew"],
  이슬비: ["drizzle"],
  이승: ["square", "squares"],
  이식: ["interests"],
  이십면체: ["icosahedron"],
  이야기: ["chat", "chats", "talk", "conversation"],
  이어폰: ["headphones", "earphone"],
  이용자: ["user", "users"],
  이유: ["reason"],
  이익: ["interests"],
  이자: ["interests"],
  이진법: ["binary"],
  이치: ["reason"],
  이콘: ["icons"],
  이퀄라이저: ["equalizer"],
  이해력: ["intelligence"],
  인가: ["approval"],
  인간: ["man", "human"],
  인감: ["stamp"],
  인공위성: ["satellite"],
  인공호흡기: ["ventilator"],
  인구통계학: ["demography"],
  인구학: ["demography"],
  인도대마: ["cannabis"],
  인디케이터: ["indicator"],
  인력거: ["rickshaw"],
  인류: ["man", "human"],
  인맥: ["network"],
  인민: ["people"],
  인민폐: ["renminbi"],
  인보이스: ["invoice"],
  인상: ["image", "face", "images"],
  인쇄공: ["printer"],
  인쇄기: ["press"],
  인쇄자: ["printer"],
  인스턴트: ["instant"],
  인식: ["recognition"],
  인용: ["quote", "quotes"],
  인원: ["staff"],
  인장: ["seal", "stamp"],
  인정하다: ["admission"],
  인조인간: ["android", "robot"],
  인지: ["cognition"],
  인칭: ["person"],
  인터폰: ["intercom"],
  인터프레터: ["interpreter"],
  일건서류: ["dossier"],
  일견: ["looks", "look"],
  일과: ["routine"],
  일괄: ["batch"],
  일기: ["weather"],
  일락: ["sunset"],
  일률: ["power"],
  일문한자: ["kanji"],
  일본만화: ["manga"],
  일본어의한자: ["kanji"],
  일산: ["parasol"],
  일자리: ["work"],
  일정: ["schedule"],
  일주야: ["day", "days"],
  일출: ["sunrise"],
  일치: ["unity"],
  읽는사람: ["reader"],
  임금: ["king", "kings"],
  임대: ["rental"],
  임무: ["task"],
  임시직원: ["temp"],
  임신: ["pregnancy"],
  입구: ["portal"],
  입금: ["deposit"],
  입력: ["input"],
  입방: ["cube"],
  입방체: ["cube"],
  입술: ["lips"],
  입장: ["angle"],
  입찰: ["bid"],
  입체: ["solids"],
  잉크: ["ink"],
  잎사귀: ["blade"],
  자국: ["track", "trail", "trace", "traces"],
  자금: ["funds"],
  자기: ["love"],
  자기자신: ["self"],
  자동계단: ["escalator"],
  자동차: ["car"],
  자동화: ["automation"],
  자료: ["data"],
  자루: ["bag", "bags"],
  자루걸레: ["mop"],
  자리: ["seat", "room", "rooms", "places"],
  자막: ["subtitles"],
  자물쇠: ["lock"],
  자뼈: ["ulna"],
  자산: ["asset"],
  자서: ["dictionary"],
  자석: ["magnet"],
  자세: ["position"],
  자승: ["square", "squares"],
  자신: ["self"],
  자연: ["nature"],
  자연력: ["element"],
  자전: ["dictionary"],
  자전거: ["bike", "bicycle"],
  자질: ["character"],
  자체: ["font", "glyphs"],
  자판: ["keyboard"],
  자형: ["font"],
  작동: ["action", "actions"],
  작물: ["crop"],
  작업: ["work"],
  작업대: ["workbench"],
  작업실: ["studio"],
  작용: ["operations", "effects"],
  작은길: ["trail"],
  작은삽화: ["vignette"],
  작은조각: ["bit"],
  작전: ["operations"],
  작품: ["work", "piece"],
  작풍: ["style"],
  잔돈: ["change", "changes"],
  잔디밭: ["grass", "lawn"],
  잔액: ["balance"],
  잔치: ["party"],
  잔학: ["cruelty"],
  잠수함: ["submarine"],
  잠자리: ["bed", "beds"],
  잡담: ["chat", "chats"],
  잡소리: ["noise"],
  잡신: ["ghost"],
  잡음: ["noise"],
  잡초: ["grass"],
  장갑: ["glove"],
  장군: ["general"],
  장난감: ["toys", "toy"],
  장대: ["pole"],
  장르: ["genres"],
  장면: ["scene"],
  장미: ["rose"],
  장미나무: ["rose"],
  장미색: ["rose"],
  장바구니: ["basket"],
  장방형: ["rectangle", "rectangles"],
  장벽: ["barrier"],
  장보기: ["shopping"],
  장서: ["library"],
  장소: ["location", "places", "place"],
  장애: ["barrier"],
  장애인: ["disabled"],
  장전: ["charge"],
  장치: ["device", "devices"],
  장화: ["boot"],
  재갈: ["bit"],
  재고: ["inventory", "stock"],
  재능: ["gift", "gifts"],
  재정: ["finance"],
  재킷: ["jacket"],
  재판소: ["court"],
  재활용: ["recycling"],
  쟁반: ["tray"],
  저가락: ["chopsticks"],
  저금: ["savings", "saving"],
  저기압: ["cyclone"],
  저녁: ["dinner"],
  저녁놀: ["sunset"],
  저울: ["scales"],
  저작: ["work", "writing"],
  저작권: ["copyright"],
  저축: ["savings", "saving"],
  저항기: ["resistor"],
  적금: ["copper"],
  적기: ["writing"],
  적분: ["integration", "integral", "integrals"],
  적외선: ["infrared"],
  적용: ["applications"],
  적용물: ["applications"],
  적집합: ["intersection"],
  적포도주: ["red"],
  전경: ["panorama", "foreground"],
  전구: ["theater", "theaters"],
  전극: ["electrodes"],
  전근: ["transfer"],
  전기: ["electricity"],
  전기용량: ["capacity"],
  전념: ["applications"],
  전등: ["lamp"],
  전람: ["cable"],
  전략: ["strategy"],
  전력: ["power", "electricity"],
  전령: ["doorbell", "messenger"],
  전류: ["current"],
  전류계: ["ammeter"],
  전망: ["vision"],
  전보: ["telegram"],
  전사: ["private"],
  전선: ["front", "cable", "wire"],
  전선군: ["front"],
  전설: ["legend"],
  전술: ["tactic"],
  전시: ["television"],
  전시회: ["show"],
  전압계: ["voltmeter"],
  전언: ["message", "messages"],
  전언판: ["forum"],
  전역: ["theater", "campaign", "theaters"],
  전음기: ["megaphone"],
  전이: ["transition", "transitions"],
  전자계산기: ["computer"],
  전자메일: ["email"],
  전자우편: ["email"],
  전장: ["fields", "field"],
  전조등: ["headlights"],
  전지: ["battery", "cell", "cells"],
  전진: ["progress"],
  전차: ["tram", "tank"],
  전철: ["subway"],
  전투: ["action", "actions"],
  전파: ["signal"],
  전하: ["charge"],
  전화: ["ring", "rings"],
  절도: ["theft"],
  절두체: ["frustum"],
  절벽: ["cliff"],
  절약: ["savings", "saving"],
  절점: ["node"],
  절차: ["procedure"],
  점검: ["check", "checks"],
  점수: ["mark", "grade"],
  점수판: ["scoreboard"],
  점심: ["lunch", "dinner"],
  점심밥: ["lunch"],
  점심식사: ["lunch"],
  점안기: ["eyedropper"],
  점자: ["braille"],
  점점점: ["ellipsis"],
  점판암: ["slate"],
  점포: ["shop"],
  점프: ["jump"],
  접근: ["approach"],
  접선: ["tangent"],
  접속: ["join"],
  접수처: ["registration"],
  접시: ["dish"],
  접시닦는사람: ["dishwasher"],
  접지: ["ground"],
  접지선: ["earth", "ground"],
  접촉: ["contact", "touch", "contacts"],
  젓가락: ["chopsticks"],
  정거장: ["station"],
  정구: ["tennis"],
  정답: ["answer"],
  정도: ["scale", "degrees"],
  정류장: ["stop", "station", "stops"],
  정면: ["front"],
  정문: ["portal"],
  정보: ["data", "information", "intelligence", "fact"],
  정보기관: ["intelligence"],
  정부: ["government"],
  정비소: ["garage"],
  정사각형: ["square", "squares"],
  정수리: ["crown"],
  정신과의사: ["shrink"],
  정신의학: ["psychiatry"],
  정원: ["garden"],
  정육면체: ["cube"],
  정의: ["definition"],
  정의역: ["domain", "domains"],
  정이십면체: ["icosahedron"],
  정전용량: ["capacity"],
  정제: ["pill", "pills"],
  정찬: ["dinner"],
  정책: ["policy"],
  정체: ["identity"],
  정체성: ["identity"],
  정치적인터내셔널: ["international"],
  정크메일: ["spam"],
  정판: ["abacus"],
  정현: ["sine"],
  젖먹이: ["baby"],
  제곱: ["square", "squares"],
  제과점: ["bakery"],
  제도: ["system"],
  제도법: ["graphics"],
  제목: ["heading", "title"],
  제스처: ["gesture"],
  제안: ["suggestion"],
  제어: ["control"],
  제어장치: ["control"],
  제조: ["production"],
  제트코스터: ["rollercoaster"],
  제품: ["product"],
  제한: ["limits"],
  젠더: ["gender"],
  조가비: ["shell"],
  조각: ["snippet", "piece"],
  조개: ["shell"],
  조건: ["conditions"],
  조국: ["land"],
  조금: ["bit"],
  조끼: ["mug"],
  조롱: ["taunt"],
  조류: ["bird"],
  조리대: ["countertops"],
  조명: ["lighting"],
  조반: ["breakfast"],
  조사: ["check", "checks", "research", "survey"],
  조성: ["tonality"],
  조세: ["tax"],
  조수: ["help", "assistant", "helper"],
  조식: ["breakfast"],
  조이스틱: ["joystick"],
  조절: ["control", "adjustments"],
  조정: ["adjustments", "calibration"],
  조제학: ["pharmacy"],
  조직: ["organization"],
  조치: ["measure"],
  조커: ["joker"],
  조항: ["article"],
  조회: ["view"],
  존재: ["life"],
  졸업: ["graduation"],
  졸업식: ["graduation"],
  종렬: ["columns", "column"],
  종료: ["end"],
  종류: ["sort", "type", "class", "feather"],
  종별: ["category"],
  종소리: ["bell"],
  종야등: ["nightlight"],
  종양학: ["oncology"],
  종업원: ["staff"],
  종이: ["paper"],
  종이접기: ["origami"],
  종점: ["terminal"],
  종지: ["close"],
  종착역: ["terminal"],
  좋아요: ["like"],
  좌석: ["seat", "places", "place"],
  좌현: ["port"],
  주간: ["day", "days"],
  주교: ["bishop"],
  주교관: ["mitre"],
  주기: ["cycle"],
  주둔지: ["station"],
  주말: ["weekend"],
  주머니: ["pocket"],
  주먹: ["fist"],
  주목: ["attention"],
  주문: ["order", "orders", "spell"],
  주방: ["kitchen"],
  주방장: ["chef"],
  주사기: ["syringe"],
  주소: ["address"],
  주식: ["share", "lunch", "stock"],
  주어: ["subject"],
  주의: ["attention"],
  주인: ["host"],
  주일: ["week"],
  주장: ["claim"],
  주전자: ["kettle"],
  주제: ["topic", "subject"],
  주차: ["parking"],
  주차장: ["parking"],
  주판: ["abacus"],
  주황색: ["orange"],
  죽은사람: ["deceased"],
  죽음: ["end"],
  줄기: ["branch", "cane"],
  줄무늬: ["band"],
  줄임표: ["ellipsis"],
  줄표: ["dash"],
  줄표시: ["barcode"],
  중간: ["middle"],
  중등학교: ["school"],
  중량: ["weight"],
  중성: ["neuter"],
  중식: ["lunch"],
  중심: ["middle"],
  중압: ["pressure"],
  중앙: ["middle"],
  즐겨찾기: ["bookmark", "bookmarks"],
  즐로티: ["zloty"],
  증가: ["increase"],
  증가량: ["increase"],
  증기: ["steam"],
  증명서: ["certificate"],
  증상: ["symptoms"],
  증서: ["certificate"],
  증언대: ["stand"],
  증정: ["presentation"],
  증후: ["symptoms"],
  지갑: ["wallet"],
  지게차: ["forklift"],
  지구: ["area", "world"],
  지구본: ["globe"],
  지구의: ["globe"],
  지국: ["branch"],
  지대: ["zone", "belt"],
  지도: ["map", "maps"],
  지력: ["intelligence"],
  지르코늄: ["zirconium"],
  지름: ["diameter"],
  지문: ["fingerprint"],
  지방: ["fat", "region"],
  지배인: ["manager"],
  지배자: ["ruler"],
  지분: ["share"],
  지불: ["payment", "payments"],
  지붕: ["roof"],
  지사: ["branch"],
  지성: ["intelligence"],
  지속: ["duration"],
  지시봉: ["pointer"],
  지시약: ["indicator"],
  지식: ["science"],
  지역: ["area", "region"],
  지우개: ["eraser"],
  지원: ["support"],
  지원군: ["volunteer"],
  지원병: ["volunteer"],
  지원자: ["volunteer"],
  지위: ["function", "position", "office", "status"],
  지점: ["location", "branch"],
  지주: ["spider"],
  지지: ["support"],
  지진: ["earthquake"],
  지진해일: ["tsunami"],
  지침: ["pointer"],
  지탱축: ["band"],
  지팡이: ["stick", "yard"],
  지평선: ["horizon"],
  지폐: ["banknote"],
  지표: ["guide", "guides"],
  지프: ["jeep"],
  지하도: ["subway"],
  지하철: ["subway"],
  지하출입구: ["area"],
  지혜: ["intelligence"],
  지휘: ["directions", "direction"],
  지휘대: ["podium"],
  직경: ["diameter"],
  직기: ["loom"],
  직무: ["function", "functions"],
  직분: ["function", "functions"],
  직사각형: ["rectangle", "rectangles"],
  직승기: ["helicopter"],
  직승비행기: ["helicopter"],
  직업: ["work", "business"],
  직원: ["staff"],
  직위: ["function", "office", "functions"],
  직장: ["work"],
  진공: ["vacuum"],
  진단: ["diagnosis"],
  진동: ["vibration"],
  진보: ["progress"],
  진상: ["fact"],
  진자: ["pendulum"],
  진지: ["meal", "food", "rice", "meals"],
  진행: ["progress"],
  진행자: ["anchor"],
  질문: ["question", "query"],
  질병: ["disease"],
  질서: ["order", "orders"],
  짐꾸러미: ["package", "packages"],
  짐수레: ["cart"],
  짐승: ["worm"],
  집단: ["group", "groups", "community"],
  집중: ["focus"],
  집필: ["writing"],
  집합: ["set"],
  징병: ["draft", "drafts"],
  징후: ["symptoms"],
  짝맞추기: ["puzzle"],
  짬찌: ["private"],
  쩨마: ["topic"],
  차고: ["garage"],
  차금: ["margin"],
  차기: ["kick"],
  차례: ["turn"],
  차륜: ["wheel"],
  차림표: ["menu"],
  차마당: ["parking"],
  차수: ["degrees"],
  차원: ["dimension", "dimensions"],
  차이: ["difference"],
  차주전자: ["teapot"],
  차징: ["charge"],
  차트: ["chart"],
  차표: ["ticket", "tickets"],
  차한잔: ["tea"],
  착륙: ["landing"],
  착함: ["good"],
  찬성: ["approval"],
  참격: ["slash"],
  참고: ["reference"],
  참조: ["reference"],
  찻잎: ["tea"],
  찻주전자: ["teapot"],
  창고: ["store", "warehouse"],
  창구: ["window", "windows"],
  창립: ["foundation"],
  창문: ["window", "windows"],
  창설: ["foundation"],
  찾기: ["search"],
  채널: ["station", "channels", "channel"],
  채팅: ["chat", "chats"],
  책갈피: ["bookmark", "bookmarks"],
  책상: ["desk"],
  책의고정축: ["band"],
  책임: ["charge"],
  챗봇: ["chatbot"],
  처녀: ["cherry"],
  처리: ["transaction"],
  처방: ["prescription", "prescriptions"],
  처방전: ["prescription", "prescriptions"],
  처음: ["start", "beginning"],
  척골: ["ulna"],
  척도: ["scale"],
  천거: ["recommendations"],
  천막: ["tent"],
  천분: ["gift", "gifts"],
  천색: ["azure"],
  천장: ["ceiling"],
  천재: ["gift", "gifts"],
  천체사진술: ["astrophotography"],
  천칭: ["scales"],
  철도: ["railway"],
  철사: ["wire"],
  철조망: ["wire"],
  첨부파일: ["attachment"],
  첨필: ["stylus"],
  첩보: ["intelligence"],
  첩자: ["spy"],
  첫소리: ["initial"],
  청각: ["hearing"],
  청구: ["claim"],
  청력: ["hearing"],
  청룡열차: ["rollercoaster"],
  청문회: ["hearing"],
  청사진: ["blueprint"],
  청소부: ["cleaner"],
  청원: ["applications"],
  청정기: ["purifier"],
  청진기: ["stethoscope"],
  체계: ["system"],
  체류: ["stay"],
  체리: ["cherry"],
  체면: ["face"],
  체스: ["chess"],
  체온계: ["thermometer"],
  체위: ["asana"],
  체재: ["stay"],
  체적: ["volume"],
  체조: ["gymnastics"],
  체중: ["weight"],
  체커판: ["checkerboard"],
  체크박스: ["checkbox"],
  체크상자: ["checkbox"],
  체크인마감시간: ["close"],
  첼라: ["wrench"],
  초고: ["draft", "drafts"],
  초고층건물: ["skyscraper"],
  초록: ["green"],
  초록색: ["green"],
  초병: ["sentry"],
  초상: ["portrait"],
  초상화: ["portrait"],
  초성: ["initial"],
  초승달: ["crescent"],
  초신성: ["supernova"],
  초인종: ["doorbell"],
  초점: ["focus"],
  초지: ["lawn"],
  초코: ["chocolate"],
  초코색: ["chocolate"],
  초콜렛: ["chocolate"],
  초콜릿: ["chocolate"],
  초콜릿색: ["chocolate"],
  촉각: ["touch", "antenna"],
  촉대: ["candlestick"],
  촌락: ["village"],
  촛대: ["candlestick"],
  총성: ["report", "reports"],
  총신: ["barrel"],
  총알: ["bullets"],
  총열: ["barrel"],
  총탄: ["bullets"],
  총화: ["sum"],
  촬영: ["cinema"],
  촬영소: ["studio"],
  최고기록: ["record"],
  최빈값: ["mode"],
  최신소식: ["update", "updates"],
  쵸콜레트: ["chocolate"],
  추골: ["hammer"],
  추기경: ["cardinal"],
  추락: ["crash"],
  추방: ["transportation"],
  추세: ["trend"],
  추억: ["memory"],
  추위: ["cold"],
  추진기: ["propeller"],
  추천: ["recommendations"],
  축구: ["football", "soccer"],
  축구공: ["football"],
  축배: ["toast"],
  축사: ["stable"],
  축일: ["holiday", "festival"],
  축전기: ["capacitor"],
  축제: ["celebration", "festival"],
  축제일: ["holiday"],
  축하: ["celebration"],
  출구: ["exit", "outlet"],
  출력: ["output"],
  출발: ["departure"],
  출산: ["delivery"],
  출처: ["source"],
  충돌: ["crash", "conflict"],
  충성: ["loyalty"],
  충성심: ["loyalty"],
  충실: ["loyalty"],
  충전기: ["charger"],
  취소: ["cancellation"],
  취침시간: ["bedtime"],
  측량: ["survey"],
  측면: ["side", "sides"],
  측정: ["measure"],
  층계참: ["landing"],
  치료: ["therapy", "medicine"],
  치수: ["dimension", "dimensions"],
  치아: ["tooth"],
  치즈: ["cheese"],
  친구: ["friends"],
  친족: ["family"],
  친척: ["family"],
  칠판: ["board", "chalkboard"],
  침대: ["bed", "beds"],
  침묵: ["silence"],
  침술: ["acupuncture"],
  침실: ["bedroom"],
  칩스: ["chip", "chips"],
  칭호: ["title"],
  카나리아: ["canary"],
  카드: ["card", "cards"],
  카드지갑: ["cardholder"],
  카라반: ["caravan"],
  카라테: ["karate"],
  카레: ["curry"],
  카메라: ["camera"],
  카바디: ["kabaddi"],
  카세트: ["cassette"],
  카아본지: ["carbon"],
  카약: ["kayak"],
  카우보이: ["cowboy"],
  카우치: ["couch", "sofa"],
  카운터: ["counter"],
  카운터톱: ["countertops"],
  카운트다운: ["countdown"],
  카지노: ["casino"],
  카타가나: ["katakana"],
  카타카나: ["katakana"],
  카테고리: ["category"],
  카트: ["cart"],
  칵테일: ["cocktail"],
  칼럼: ["columns", "column"],
  칼새: ["swift"],
  칼파스: ["sausage"],
  캐릭터: ["character"],
  캐빈: ["cabin"],
  캐시: ["cash"],
  캐패시터: ["capacitor"],
  캔디: ["candy"],
  캘린더: ["calendar", "calendars"],
  캠페인: ["campaign"],
  캠프파이어: ["campfire"],
  캠핑: ["camping"],
  캡슐: ["capsule"],
  커넥션: ["connection"],
  커리: ["curry"],
  커맨드: ["command", "commands"],
  커뮤니케이션: ["communication"],
  커뮤니티: ["community"],
  커서: ["cursor"],
  커튼: ["curtains"],
  커패시터: ["capacitor"],
  커피: ["coffee"],
  커피색: ["coffee"],
  커피콩: ["coffee"],
  컨디션: ["conditions"],
  컨베이어: ["conveyor"],
  컨펌: ["confirmation"],
  컬렉션: ["collections"],
  컬링: ["curling"],
  컴퓨터: ["computer"],
  컴퓨터바이러스: ["virus"],
  컵받침: ["saucer", "coaster"],
  케밥: ["kebab"],
  케이블: ["cable"],
  케이크: ["cake"],
  코냑: ["brandy"],
  코너: ["corner", "corners"],
  코드: ["code"],
  코로나바이러스: ["coronavirus"],
  코로나비루스: ["coronavirus"],
  코멘트: ["comment", "comments"],
  코미디: ["comedy"],
  코믹: ["comedy"],
  코믹스: ["comic"],
  코스: ["course"],
  코스터: ["coaster"],
  코인: ["coin", "coins"],
  코트: ["coat", "court"],
  코티지: ["cottage"],
  콘센트: ["socket"],
  콘테이너: ["container"],
  콘텐츠: ["content", "contents"],
  콜라보: ["collaboration"],
  콜라보레이션: ["collaboration"],
  콜라주: ["collage"],
  콤포스트: ["compost"],
  콤퓨터: ["computer"],
  콤플렉스: ["complex"],
  콧수염: ["moustache"],
  쿠키: ["cookie"],
  쿠폰: ["coupon"],
  쿼리: ["query"],
  쿼터: ["quarter"],
  퀴즈: ["quiz"],
  크기: ["size"],
  크라운: ["crown"],
  크래시: ["crash"],
  크랙: ["crack"],
  크레디트: ["credit", "credits"],
  크레센트: ["croissant"],
  크레센트롤빵: ["croissant"],
  크레인: ["crane"],
  크로뮴: ["chromium"],
  크로스: ["cross"],
  크로스워드: ["crossword"],
  크롬: ["chromium"],
  크루아상: ["crescent", "croissant"],
  크리스탈: ["crystal"],
  크리켓: ["cricket"],
  크림: ["cream"],
  큰까마귀: ["raven"],
  큰불: ["fire"],
  클라우드: ["cloud"],
  클래스: ["class"],
  클럭: ["clock"],
  클럽: ["club", "clubs"],
  클로버: ["clover", "club"],
  클로징: ["close"],
  클릭: ["click"],
  클린: ["clean"],
  클립: ["video"],
  클립보드: ["clipboard"],
  키보드: ["keyboard"],
  키오스크: ["kiosk"],
  킥보드: ["scooter"],
  킥스쿠터: ["scooter"],
  타겟: ["target"],
  타깃: ["target"],
  타는곳: ["platform"],
  타래: ["lock"],
  타륜: ["wheel"],
  타워: ["tower"],
  타원: ["oval", "ellipse"],
  타월: ["towel"],
  타이머: ["timer"],
  타이틀: ["title"],
  타이포그라피: ["typography"],
  타이포그래피: ["typography"],
  타일: ["tile"],
  타입: ["type"],
  타카: ["taka"],
  타파스: ["tapas"],
  탁상: ["desktop"],
  탁자: ["table"],
  탄산나트륨: ["soda"],
  탄산음료: ["soda"],
  탄소: ["carbon"],
  탄알: ["bullets"],
  탄젠트: ["tangent"],
  탄환: ["bullets"],
  탈것: ["transportation"],
  탈력감: ["crash"],
  탈출: ["flight", "flights"],
  탐구: ["exploration"],
  탐사: ["exploration"],
  탐정: ["detective"],
  탐지: ["detection"],
  탐지기: ["radar"],
  탐험: ["exploration"],
  탑승구: ["gate"],
  태산: ["mountain", "mountains"],
  태스크: ["task"],
  태양: ["sun"],
  태음: ["moon"],
  태풍: ["typhoon"],
  택시: ["taxi"],
  탱크: ["tank"],
  터널: ["tunnel"],
  터미널: ["station", "terminal"],
  터빈: ["turbine"],
  터치: ["touch"],
  터치패드: ["touchpad"],
  턱받이: ["bib"],
  털실: ["yarn"],
  테니스: ["tennis"],
  테두리: ["ground"],
  테레비: ["television"],
  테마: ["topic"],
  테스트: ["test"],
  테슬라: ["tesla"],
  테이블: ["table"],
  테이크아웃: ["takeout"],
  테이프: ["tape"],
  텍스트: ["text"],
  텐트: ["tent"],
  텔레비: ["television"],
  텔레비전: ["television"],
  텔레비죤: ["television"],
  템플렛: ["template"],
  토끼: ["rabbit"],
  토끼굴: ["subway"],
  토너먼트: ["tournament"],
  토네이도: ["tornado"],
  토대: ["foundation"],
  토론: ["forum"],
  토론회: ["forum"],
  토막: ["chop"],
  토막고기: ["chop"],
  토스트: ["toast"],
  토양: ["earth", "ground"],
  토지: ["land", "plot"],
  토치: ["flashlight"],
  토큰: ["token", "tokens"],
  토픽: ["topic"],
  톱니: ["cog", "tooth"],
  통과: ["transit"],
  통과암호: ["password"],
  통나무: ["log", "logs"],
  통발: ["pot"],
  통보문그림기호: ["emoticon"],
  통신: ["communication"],
  통역: ["interpreter"],
  통역사: ["interpreter"],
  통역인: ["interpreter"],
  통역자: ["interpreter"],
  통제: ["control"],
  통조림: ["can"],
  통지: ["notification", "notifications"],
  통치: ["rule"],
  통치자: ["ruler"],
  통풍: ["ventilation"],
  통합: ["integration"],
  통행료: ["toll"],
  통화: ["currency", "bell", "call", "calls"],
  퇴비: ["compost"],
  퇴적물: ["deposit"],
  투구: ["helmet", "delivery"],
  투구법: ["delivery"],
  투그릭: ["tugrik"],
  투어: ["tour"],
  투영기: ["projector"],
  투입: ["input"],
  투표: ["vote", "ballot", "poll"],
  투표용지: ["ballot"],
  투표지: ["ballot"],
  툴바: ["toolbar"],
  툴박스: ["toolbox"],
  튜브: ["tube", "tubes"],
  튤립: ["tulip"],
  트라이앵글: ["triangle", "triangles"],
  트래커: ["trackers", "tracker"],
  트래픽: ["traffic"],
  트랙: ["track"],
  트랙타: ["tractor"],
  트랙터: ["tractor"],
  트랜스젠더: ["transgender"],
  트랜잭션: ["transaction"],
  트램: ["tram"],
  트랩: ["ramp"],
  트럭: ["truck"],
  트렁크: ["suitcase"],
  트레이: ["tray"],
  트레이닝: ["training"],
  트레인: ["train"],
  트레일: ["trail"],
  트레일러: ["trailer"],
  트렌드: ["trend"],
  트로피: ["trophy"],
  트리: ["tree", "trees"],
  트리거: ["trigger"],
  특질: ["quality", "character", "attributes"],
  특징: ["feature"],
  틈새: ["gap"],
  티뷔: ["television"],
  티브이: ["television"],
  티비: ["television"],
  티켓: ["ticket", "tickets"],
  티파트: ["teapot"],
  티팟: ["teapot"],
  티포트: ["teapot"],
  파괴: ["destruction"],
  파노라마: ["panorama"],
  파도: ["wave", "waves"],
  파도타기: ["surfing"],
  파라솔: ["parasol"],
  파라슈트: ["parachute"],
  파랑새: ["roller"],
  파랑새과: ["roller"],
  파비콘: ["favicon"],
  파빌리온: ["pavilion"],
  파산: ["crash"],
  파생어: ["derivatives"],
  파운데이션: ["foundation"],
  파운드: ["pound"],
  파이: ["pie"],
  파이프: ["pipe"],
  파이프라인: ["pipeline"],
  파인더: ["viewfinder"],
  파일: ["file", "files"],
  파트너: ["partner"],
  파티: ["party"],
  판다: ["panda"],
  판막: ["valve"],
  판매: ["sale"],
  판매점: ["shop", "kiosk"],
  판자: ["board"],
  판지: ["cardboard", "cardboards"],
  팔각형: ["octagon"],
  팔걸이의자: ["armchair"],
  팔꿈치: ["elbow"],
  팔레트: ["palette"],
  팔로우: ["follow"],
  팔면체: ["octahedron"],
  팔목: ["wrist"],
  팝콘: ["popcorn"],
  팟캐스트: ["podcasts", "podcast"],
  패널: ["panel", "panels"],
  패배: ["loss"],
  패비콘: ["favicon"],
  패스: ["path"],
  패스워드: ["password"],
  패스포트: ["passport"],
  패치: ["patch"],
  패키지: ["package", "packages"],
  패킷: ["package", "packet", "packages"],
  패킹: ["package", "packages"],
  패턴: ["pattern"],
  팩스: ["fax"],
  팩시밀리: ["fax"],
  팬티: ["pants"],
  팸플릿: ["booklet"],
  팽창: ["expansion"],
  퍼브: ["bar", "bars"],
  퍼센트: ["percent"],
  퍼센티지: ["percentage"],
  퍼즐: ["puzzle"],
  펀치: ["punch"],
  펌프: ["pump"],
  페달: ["pedal"],
  페리: ["ferry"],
  페소: ["peso"],
  페이지: ["page", "pages"],
  페인트: ["paint"],
  페지: ["page", "pages"],
  펜던트: ["pendant"],
  펜촉: ["nib"],
  펜치: ["pliers"],
  펜타그램: ["pentagram"],
  펠메니: ["dumpling"],
  편복: ["bat"],
  편자: ["editor", "horseshoe"],
  편지: ["letter", "letters"],
  편집: ["edit"],
  편집기: ["editor"],
  편집인: ["editor"],
  편집자: ["editor"],
  평가: ["rating"],
  평균: ["average"],
  평면: ["plane"],
  평면도: ["plan"],
  평민: ["people"],
  평방: ["square", "squares"],
  평안: ["peace"],
  평정: ["peace"],
  평행사변형: ["parallelogram"],
  평화: ["peace"],
  포도: ["grape"],
  포도당: ["glucose"],
  포도색: ["grape"],
  포도주: ["wine"],
  포도주빛의: ["wine"],
  포도주색: ["wine"],
  포럼: ["forum"],
  포로: ["captive"],
  포말경기: ["bubble", "bubbles"],
  포맷: ["format"],
  포볼: ["walk"],
  포워드: ["forward"],
  포인터: ["pointer"],
  포인트: ["switch", "point", "points"],
  포장: ["package", "packages"],
  포커: ["poker"],
  포켓: ["pocket"],
  포켓볼: ["pool"],
  포크: ["fork"],
  포크리프트: ["forklift"],
  포탄: ["shell"],
  포털: ["portal"],
  포트: ["pot", "port"],
  포트와인: ["port"],
  포화: ["saturation"],
  폭발: ["explosion"],
  폭사: ["radiation"],
  폭탄: ["bomb"],
  폭포: ["waterfall"],
  폭풍: ["tornado", "storm", "hurricane"],
  폭풍우: ["hurricane"],
  폰트: ["font"],
  폴더: ["folder", "folders", "directory"],
  표백제: ["bleach"],
  표본: ["specimen"],
  표식: ["mark"],
  표적: ["target"],
  표절: ["plagiarism"],
  표정: ["face", "expression"],
  표제: ["caption", "heading", "title", "captions"],
  표준: ["standard"],
  표지: ["sign", "signs"],
  표지판: ["signpost"],
  표창: ["award"],
  표현: ["expression"],
  푯말: ["signpost"],
  풀밭: ["grass", "lawn"],
  품삯: ["price"],
  품질: ["quality"],
  풋볼: ["football", "soccer"],
  풍경: ["landscape"],
  풍력: ["wind"],
  풍선: ["balloon"],
  풍속: ["custom"],
  풍습: ["custom"],
  풍차: ["windmill"],
  프라이버시: ["privacy"],
  프락치: ["plant"],
  프랑: ["franc"],
  프랑스빵: ["baguette"],
  프런트: ["front", "registration"],
  프레스: ["press"],
  프레이즈: ["phrases"],
  프레임: ["frame", "frames"],
  프레젠테이션: ["presentation"],
  프로: ["percent", "broadcast", "pro", "program"],
  프로그래머: ["developer"],
  프로그램: ["broadcast", "program", "show"],
  프로세스: ["process"],
  프로젝터: ["projector"],
  프로토콜: ["protocol"],
  프로파일: ["profile"],
  프로판: ["propane"],
  프로페인: ["propane"],
  프로펠러: ["propeller"],
  프로필: ["profile"],
  프록시: ["proxy"],
  프록시서버: ["proxy"],
  프롬프트: ["prompt"],
  프리즘: ["prism"],
  프린터: ["printer"],
  플라스크: ["flask"],
  플라이어: ["pliers"],
  플래그: ["flag"],
  플래시: ["flash"],
  플래카드: ["banner"],
  플랜트: ["plant"],
  플랫: ["flat"],
  플랫트홈: ["platform"],
  플랫폼: ["platform"],
  플랫홈: ["platform"],
  플러그: ["plug", "plugs"],
  플레이: ["play"],
  플레이리스트: ["playlist"],
  플레이어: ["player"],
  플로피: ["floppy"],
  플롯: ["plot"],
  피고석: ["dock"],
  피난처: ["shelter"],
  피드: ["feed"],
  피드백: ["feedback"],
  피라미드: ["pyramid"],
  피리: ["pipe"],
  피벗: ["pivot"],
  피부과학: ["dermatology"],
  피부색: ["color", "colors"],
  피스: ["piece"],
  피싱: ["phishing"],
  피아노: ["piano"],
  피임약: ["pill", "pills"],
  피자: ["pizza"],
  피크닉: ["picnic"],
  피통: ["health"],
  피트: ["foot"],
  피펫: ["pipette"],
  피혁: ["hide"],
  픽셀: ["pixel"],
  필드: ["fields", "field"],
  필라멘트: ["filament"],
  필름: ["film"],
  필터: ["filter", "filters"],
  필획: ["stroke"],
  하나미: ["hanami"],
  하늘색: ["azure"],
  하늬: ["west"],
  하드웨어: ["hardware"],
  하루: ["day", "days"],
  하리켄: ["hurricane"],
  하상: ["bed", "beds"],
  하양: ["white"],
  하이라이터: ["highlighter"],
  하이라이트: ["highlight"],
  하이킹: ["hike", "hiking"],
  하키: ["hockey"],
  하트: ["heart", "hearts"],
  학과: ["school", "department", "subject"],
  학교: ["school"],
  학급: ["grade"],
  학년: ["class", "grade"],
  학생: ["student"],
  학설: ["doctrine"],
  학원: ["school"],
  학위: ["degrees"],
  학점: ["credit", "credits"],
  학파: ["school"],
  한동안: ["spell"],
  한랭사: ["lawn"],
  한물: ["flood"],
  한병의분령: ["bottle"],
  한자: ["kanji"],
  한정사: ["attributes"],
  한참: ["spell"],
  할인: ["discount"],
  함수: ["function", "functions"],
  함정: ["plant"],
  합계: ["total", "sum"],
  합자: ["ligature"],
  합작: ["collaboration"],
  합집합: ["union"],
  항공기: ["airplane", "plane"],
  항공사: ["airline", "airlines"],
  항공역: ["airports", "airport"],
  항공편: ["flight", "flights"],
  항공회사: ["airline", "airlines"],
  항구: ["port"],
  항로: ["course"],
  항목: ["article"],
  항법: ["navigation"],
  항성: ["star", "stars"],
  항해: ["navigation", "sailing"],
  항행: ["navigation"],
  해골: ["skeleton"],
  해넘이: ["sunset"],
  해답: ["answer"],
  해돋이: ["sunrise"],
  해머: ["hammer"],
  해발: ["altitude"],
  해변: ["beach"],
  해산: ["delivery"],
  해석자: ["interpreter"],
  해석학: ["analytics"],
  해설자: ["interpreter"],
  해시: ["hash"],
  해시태그: ["hashtag"],
  해일: ["tsunami"],
  해제: ["cancellation"],
  해질녘: ["dark"],
  해협: ["channels", "channel"],
  핸드백: ["handbag"],
  핸드볼: ["handball"],
  핸드볼공: ["handball"],
  핸드세이크: ["handshake"],
  핸드셰이크: ["handshake"],
  핸드셰이킹: ["handshake"],
  핸들링: ["handball"],
  햄버거: ["hamburger"],
  행동: ["action", "actions"],
  행렬: ["train", "matrix"],
  행사: ["event", "function", "functions"],
  행성: ["planet"],
  향기: ["fragrance", "perfume"],
  향수: ["perfume"],
  향참외: ["melon"],
  허리띠: ["belt"],
  허리케인: ["hurricane"],
  허무감: ["crash"],
  허파: ["lungs"],
  헌팅: ["pickup"],
  헛간: ["barn"],
  헤드라이트: ["headlights"],
  헤드라인: ["headline"],
  헤드셋: ["headset"],
  헤드폰: ["headphones", "headphone"],
  헤딩: ["header"],
  헤이즈: ["haze"],
  헬기: ["helicopter"],
  헬리콥터: ["helicopter"],
  헬멧: ["helmet"],
  현금: ["money", "cash"],
  현미경: ["microscope"],
  현상액: ["developer"],
  현수막: ["banner"],
  현실: ["reality", "fact"],
  현재: ["present"],
  현지인: ["native"],
  현찰: ["cash"],
  혈액: ["blood"],
  혈액검사: ["blood"],
  혈연: ["blood"],
  혈통: ["blood"],
  혐오: ["dislike"],
  협력: ["collaboration"],
  협박: ["threat"],
  협업: ["collaboration"],
  협위: ["threat"],
  형광펜: ["highlighter"],
  형무소: ["prison"],
  형사: ["detective"],
  형상: ["forms", "form"],
  형식: ["shapes", "shape", "forms", "form"],
  혜성: ["comet"],
  호구: ["pushover"],
  호박: ["pumpkin"],
  호스트: ["host"],
  호접: ["butterfly"],
  호주머니: ["pocket"],
  호출기: ["pager"],
  호케이: ["hockey"],
  호텔: ["hotel", "hotels"],
  호프: ["hop"],
  호흡기학: ["pulmonology"],
  혼인: ["union"],
  혼합주: ["cocktail"],
  혼합하다: ["blend"],
  홍당무: ["carrot"],
  홍수: ["flood"],
  홍예: ["rainbow"],
  화가: ["artist"],
  화덕: ["fire"],
  화랑: ["gallery"],
  화륜: ["wreath"],
  화면: ["screen", "wallpaper"],
  화면보호기: ["screensaver"],
  화목: ["peace"],
  화산: ["volcano"],
  화살: ["arrow", "arrows"],
  화살표: ["arrow", "arrows"],
  화상: ["image", "images"],
  화소: ["pixel"],
  화실: ["studio"],
  화염: ["flame"],
  화이트보드: ["whiteboard"],
  화자: ["speaker"],
  화장실: ["toilet", "restroom"],
  화재: ["fire"],
  화제: ["topic"],
  화집합: ["union"],
  화채: ["punch"],
  화초: ["plant"],
  화폐: ["currency", "money"],
  화필: ["paintbrush"],
  화학식: ["formula"],
  화환: ["wreath"],
  확성기: ["speaker", "megaphone"],
  확인: ["check", "checks", "confirmation"],
  확장: ["expansion"],
  환각: ["vision"],
  환경: ["environment"],
  환기: ["ventilation"],
  환불: ["refund"],
  환불금: ["refund"],
  환상: ["ghost"],
  환승: ["change", "changes", "connection"],
  환시: ["vision"],
  환약: ["pill", "pills"],
  환영: ["ghost"],
  환원: ["reduction"],
  환자: ["patient"],
  활대: ["yard"],
  활동: ["activity"],
  황도대: ["zodiac"],
  황도십이궁: ["zodiac"],
  황혼: ["night", "twilight", "sunset"],
  황후: ["queen"],
  횃대: ["rack"],
  횃불: ["torch"],
  회답: ["reply", "answer"],
  회로: ["circuit"],
  회상: ["memory"],
  회신: ["answer"],
  회원: ["member", "membership"],
  회의: ["meeting", "conference", "assembly"],
  회전: ["turn", "rotation"],
  회전교차로: ["roundabout"],
  회전놀이기구: ["roundabout"],
  회전목마: ["carousel"],
  회전무대: ["roundabout"],
  회합: ["meeting"],
  회화: ["picture", "talk", "conversation"],
  효과: ["effects"],
  효력: ["effects"],
  후드: ["hood", "hoodie"],
  후드티: ["hood", "hoodie"],
  후렴구: ["hook"],
  후식: ["dessert"],
  후추: ["pepper"],
  후프: ["hoop"],
  훈련: ["training", "drill"],
  훈장: ["order", "medal", "orders"],
  훌라: ["hula"],
  훔침: ["theft"],
  휠체어: ["wheelchair"],
  휴가: ["holiday"],
  휴게: ["pause", "break"],
  휴식: ["rest"],
  휴일: ["holiday"],
  휴지: ["pause"],
  휴지통: ["bin"],
  흉부: ["chest"],
  흐름: ["stream", "flow", "current"],
  흐리브냐: ["hryvnia"],
  흔적: ["track", "trail", "trace", "traces"],
  흠칫함: ["start"],
  흡연: ["smoking"],
  흥미: ["interests"],
  흥행: ["show"],
  희곡: ["play"],
  희극: ["comedy"],
  희망: ["wish"],
  흰색: ["white"],
  히라가나: ["hiragana"],
  히터: ["heater"],
};
